### ISSUE TITLE
Minitest?

### ISSUE THREAD

**Issue by epinault** [elabs/pundit#204]
Do you have an example of how you would test it with minitest? Or minitest spec?

**Comment by rpearce** [comment]
For anybody who has nested `describe` issues in the future, based on the issue described [here](https://github.com/blowmage/minitest-rails/issues/166) and the [solution I came up with](https://github.com/blowmage/minitest-rails/issues/166#issuecomment-192254973), if you're having nested `describe` problems, then try changing your permit method to
```ruby
def permit(user, record, action)
  test_name = self.class.ancestors.select { |a| a.to_s.match(/PolicyTest/) }.first
  klass = test_name.to_s.gsub(/Test/, '')
  klass.constantize.new(user, record).public_send("#{action.to_s}?")
end
```

**Comment by pbougie** [comment]
Unfortunately this didn't work as expected. My test classes also use a `describe` block at the top-level (unlike the above example), i.e.

```ruby
describe PostPolicy do
  ...
end
```

Therefore my `permit()` method is as follows:

```ruby
def permit(user, record, action)
  index = self.class.name.index('Policy')
  klass = self.class.name[0, index+6]
  klass.constantize.new(user, record).public_send("#{action.to_s}?")
end
```

This solution seems to work for namespaced policies and nested describe blocks.
