### ISSUE TITLE
Ensuring policy_scope is used in controller even if views fetch resources with policy_scope

### ISSUE THREAD

**Issue by valscion** [elabs/pundit#207]
Hi,

we're having a pickle with the `verify_policy_scoped` function, used to ensure controllers perform authorization checking even when fetching scopes.

The problem is that in our application, we need to show users a count of resources of one type where they have access to. To do this, we use `policy_scope(Resource).size` to fetch the size.

But, alas, there lies the issue. We can no longer rely on `after_action :verify_policy_scoped, only: :index` to catch our leaky index controller actions, because of [`policy_scope` method setting a flag always when called](https://github.com/elabs/pundit/blob/c67d05d082173993d0132b7179f44c202fd9701d/lib/pundit.rb#L81).

We are a little baffled and would like your opinion on how to move forward and whether this could be remedied with some sort of an improvement to the `policy_scope` method. We thought of:

1. Adding a new, optional parameter to the `policy_scope` method which stops the `@_pundit_policy_scoped` instance variable from being set
2. Creating a new method for ensuring the model class which was loaded (say, `Comment`) was resolved with `policy_scope` in `CommentsController` by checking that the controller name matches the model which was loaded
3. Removing the `after_action :verify_policy_scoped` callback altogether as it brings us false sense of security

We would really like your opinion on this before moving forward with any solution. If we can come up with a solution that pleases everyone, I believe we'd be able to craft a PR for it.

Thanks for the amazing work with Pundit!

**Comment by exciton** [comment]
Couldn't you call verify_policy_scoped before your view renders? As in call it at the end of your controller before it renders the view?

In any case the after_filter doesn't stop the controller from doing it's thing, it just raises an exception to alert you that you let someone through. You should be finding these holes in tests not in production!

**Comment by VesQ** [comment]
> Couldn't you call verify_policy_scoped before your view renders? As in call it at the end of your controller before it renders the view?

That would be quite cumbersome, unless you have some nice way of hooking to some callback in Rails to do exactly that. We were just using the `verify_policy_scoped` as a quick aid in finding the controllers which didn't run proper authorizations.

> You should be finding these holes in tests not in production!

That is true. It just requires too much effort to remember to test each and every one controller action if they haven't been written with TDD in the first place, and even then some code paths might slip past those tests. It should never hurt to have the last line of defense in the shape of automatic error reporting in place.

**Comment by jnicklas** [comment]
Hmm, this is tricky. I don't actually know what a good solution to this would be. I think the way you're using `policy_scope` is legitimate. I think the only way this is fixable is not exposing `policy_scope` as a `helper_method`, and instead having a separate helper which exposes a different `policy_scope` method which does not set the flag. That's somewhat cumbersome, but it's as close as we can get, I think.

**Comment by jnicklas** [comment]
I've created a PR which fixes this, but I'm not sure about this. The solution is a bit ugly, IMO.
