### ISSUE TITLE
Conversation about authorization, business logic, and custom error messages

### ISSUE THREAD

**Issue by uberllama** [elabs/pundit#212]
Have been having an interesting conversation with some colleagues today and was wondering where you folks stand on it.

The question is: where do you draw your line between authorization and business logic/context? Do you use Pundit purely do define *who* can do *what* based on their role, or do you bring your deeper contexts into the picture?

Here's a plain english version of the scenario I'm dealing with:

Our system has a User model, a Post model, and an Event model. Users have roles ("admin" and "user").

* Post `belongs_to` Event, but can also stand alone.
* Any user of any role can create Posts not associated with an Event.
* Admin users can create Posts for any Event.
* Regular users can only create Posts for Events that haven't passed (if they try to create an Event for a past Post, they should get a custom error message).

### Option 1 Put everything in a Pundit Policy

If I were to do this all in Pundit, the PostPolicy and controller would look something like this:

```ruby
class PostPolicy

  def create?
    user.admin? || record.event_id.nil? || record.event.ends_at > Time.current
  end

end

class PostsController < ApplicationController

  before_action :set_post

  def create
    authorize @post
    if @post.save...
  end

  private

  def set_post
    @post = current_user.posts.build(post_params)
  end

end
```

This works... with caveats:

1. Pro: the policy could be used within a view to fully represent the rules around creating a Post.
2. Grey area: We're getting into tertiary data by looking at the record's Event association. This is a slippery slope.
3. Con: We don't have the ability to return a custom error message in the case of an expired Event (do we?). If authorization fails for whatever reason, you can only generate a singular error message based off the exception on `PostPolicy#create`.

### Option 2 Create multiple policies

```ruby
class PostPolicy

def create?
  record.event_id.nil? || record.event.ends_at > Time.current
end
```

```ruby
class AdminPostPolicy

def create?
  user.admin?
end
```

Assuming we could split policies cleanly along role lines, we might be able to do something like this, which opens up slightly more messaging options. Uncertain at this time, so this is the least fleshed out example.

### Option 3 Use Pundit purely for role checking (signed in, can create Posts) and put business logic in controllers

```ruby
class PostPolicy < ApplicationPolicy
  # ApplicationPolicy ensures user is logged in
end

class PostsController < ApplicationController

  before_action :set_post
  before_action :set_event

  def create
    authorize @post
    if @post.save...
  end

  private

  def set_post
    @post = current_user.posts.build(post_params)
  end

  def set_event
    return unless params[:post][:event_id].present?
    @post.event = Event.find(params[:post][:event_id])
    render_errors("custom message") unless current_user.admin? || @post.event.ends_at > Time.current
  end
```

It gets the job done, and can be different if we have a PostsController under /admin, but can end up fairly wet. Also, we lose the singular authority on when a user can create a post if we need the same total logic in the view.

### Option 4 Use Pundit purely for role checking (signed in, can create Posts) and put business logic in service objects

```ruby
class PostPolicy < ApplicationPolicy
  # ApplicationPolicy ensures user is logged in
end

class PostsController < ApplicationController

  def create
    post_creator = PostCreator.new(post_params, current_user)
    authorize post_creator.post, :create?
    if post_creator.save
      render post_creator.post
    else
      render_errors(post_creator.errors)
    end
  end

class PostCreator

  attr_accessor :post, :errors, :current_user

  def initialize(params, current_user)
    self.current_user = current_user
    self.post = current_user.posts.build(params)
  end

  def save
    if current_user.admin? || post.event_id.nil? || post.event.ends_at > Time.current
      post.save
    else
      self.errors = "custom message"
      false
    end
  end
end
```

Cleaner than controllers, but again you've split out your authority into two places. Also, I originally had the pundit authorize call within the service object but don't actually know if that's possible.

Another option would be to pass in the current_user context to the model and run the event check as a validation, but that is exceedingly gross, and I find my models are getting thinner and thinner these days (basically just wrappers around the table with rudimentary validation).

Feedback appreciated. Cheers.

**Comment by damien** [comment]
Great discussion! I think this is a common need a lot of people using authentication systems run into; the team I'm on certainly is. Any chance of some of this thread making it into the Pundit wiki or README?

**Comment by vasilakisfil** [comment]
hmm not sure, we haven't event reached a consensus here! But @damien if you have any suggestion let us know, personally I mainly build APIs and I am running to the same problem all the time!

**Comment by damien** [comment]
A developer on my team kindly made a PR that implements this within our own codebase. He was thinking about making a gem that did this, I'll see if I can have him or I make an excerpt of the solution so we can get feedback from you guys.

**Comment by damien** [comment]
Update: My good friend @LuisDehar published a gemified version of an initial solution to this problem: https://github.com/luisdaher/pundit_custom_errors

**Comment by jnicklas** [comment]
@damien @luisdaher: this actually seems like a pretty nice solution. I'm a bit worried about the statefulness of it, since policies are cached, but maybe that's just being overly cautious. This is how ActiveRecord does error conditions as well, so it's not without precedent (although I think it's a bit of a bad idea in AR as well, to be honest).

If you want to provide a PR to integrate this functionality into Pundit I think I'd be in favour of merging that. @thomasklemm what do you think?

**Comment by damien** [comment]
@jnicklas That would be an attractive proposal for the org I work at; maintaining such a library takes a lot of work and getting it into the pundit mainline would ensure support/compatibility for this functionality doesn't go away in future versions. I may be able to get the go ahead to allocate engineering time to this, but failing that I wouldn't mind drafting a PR for this over a few odd weekends. @luisdaher: thoughts?

**Comment by luisdaher** [comment]
@damien @jnicklas I agree. @damien , I don't mind using some of my free time to draft a PR as well :)

**Comment by jnicklas** [comment]
Closing this for now. Please send a PR if you're still interested in this.

**Comment by damien** [comment]
Should I take this to mean that the proposed changes for custom error messages are acceptable to pundit core? If so, I'll see what I can do about drafting a PR for this.

**Comment by openface** [comment]
@damien I'd be interested in this PR.  I'm currently having to create custom query methods to accommodate needing to have specific error messages.  Ie: `#update_foo?` `#update_bar?` etc.

**Comment by vraravam** [comment]
@jnicklas - the closing comment is ambiguous to me. Is this functionality present in pundit mainline as of now?
