### ISSUE TITLE
unable to find policy ArrayPolicy

### ISSUE THREAD

**Issue by acrogenesis** [elabs/pundit#213]
Pundit is unable to find class for a CollectionProxy(Array) which contains several elements of a Model inside

**Comment by darylprickett** [comment]
I think you might have a subtle security bug in your controller code. A single authorize check will determine if the controller action is valid. In your case you are calling authorize multiple times and I think your last result will determine if the action can run. Have you tested this using an array with mixed values like [true, true, false]?

**Comment by acrogenesis** [comment]
@darylprickett Tried what you say and when a instance of authorize calls a raise it fails to update. To simplify the process I made a method on application_controller.rb

```ruby
def authorize_many(model_collection)
    model_collection.each do |model_instance|
      authorize model_instance
    end
  end
```

**Comment by jnicklas** [comment]
`authorize` is meant to be used with a single object. I think that's well documented, and the fact that it doesn't work with an Array isn't really an "issue", so I'm closing this. Let's continue discussing this in #256 :)
