### ISSUE TITLE
Can't find policy method

### ISSUE THREAD

**Issue by jpstokes** [elabs/pundit#221]
I'm running a feature test using capybara, but I'm getting the following error:

    undefined method `edit?

The method is defined in my policy file but for some reason it's not being found.

    def job_openings
        authorize current_user, :edit?
        @company = current_user.company
        @jobs = @company.jobs.order 'created_at DESC'
    end

**Comment by jnicklas** [comment]
Please re-read the README. You probably don't want to pass `current_user` to `authorize` from the looks of it.

**Comment by jpstokes** [comment]
OK...@jnicklas, I'm still having this problem but I'll try doing it without using current_user.

**Comment by jpstokes** [comment]
That suggestion fixed it...thx.
