### ISSUE TITLE
Make authorize a module method

### ISSUE THREAD

**Issue by scottjacobsen** [elabs/pundit#226]
I've run into cases where it would be nice to use the `authorize` method outside a controller. It would be handy to be able to do `Pundit.authorize(user, record, :edit?)` where that method would raise `Pundit::NotAuthorizedError` if the action is not authorized.

It seems like it would be a simple matter of making the current `authorize` method a module method that takes three arguments - `user, record, query`, and making the current `authorize` instance method delegate to that method.

I would be happy to submit a PR if that sounds like it is worth doing.

**Comment by openface** [comment]
Any progress on getting this feature implemented?

**Comment by scottjacobsen** [comment]
As far as I know my PR is ready to go.

**Comment by scottjacobsen** [comment]
Closed by 56a8bdee5
