### ISSUE TITLE
permissions :show?, :update?, :destroy? do ....

### ISSUE THREAD

**Issue by timolehto** [elabs/pundit#228]
Hi,

I really appreciate the possibility to list multiple actions with the permissions method on the specs as it can save so much space and make the specs actually read better (less duplication, more DRY). However, when the shit hits the fan it's real pita. You don't know which fan it hit, so then the first thing you'll have to do is to somehow tweak the test. Either duplicate the test for all methods or then run the spec multiple times starting with one method and the adding more one by one as you clear them. E.g. here is a sample output from a test where permission was not granted for destroy. From the output you can not know what is failing.

```
Failure/Error: it { is_expected.to permit(current_user, target) }
       Expected Example::UserPolicy to grant show?, update?, and destroy? on #<Example::User:0x00000101325030> but it didn't
```

If the error message was customised to include information about which of the methods were unexpectedly granted/denied, e.g. something like this would already be an enormous improvement:
```
Failure/Error: it { is_expected.to permit(current_user, target) }
       Expected Example::UserPolicy to grant show?, update?, and destroy? on #<Example::User:0x00000101325030> but it didn't grant destroy?
```

Another option is that it could be possible for it to kind of dynamically copy and run the test separately for each case. That would be even better in a sense, because then on the Rspecs output each method would be listed as a separate fail/success and you wouldn't need to so carefully examine the output of the test to figure out which parts of the test are really failing. IMHO it would then better adhere to good testing principles. Not exactly sure if this is possible, though. The output would not need to changed at all from the current, but it would naturally read out better:

```
Failure/Error: it { is_expected.to permit(current_user, target) }
       Expected Example::UserPolicy to grant destroy? on #<Example::User:0x00000101325030> but it didn't
```

**Comment by jnicklas** [comment]
#229 is merged, which should fix this at least well enough for now.
