### ISSUE TITLE
Best practices for authorizing create? based on parent object

### ISSUE THREAD

**Issue by ajb** [elabs/pundit#231]
(possible duplicate)

Which is correct? Or am I missing something?

### Option A:

```rb
class LabelPolicy
...

  def create?
    label.project.user == user
  end
end

policy(Label.new(project: @project)).create?
```

### Option B:

```rb
class ProjectPolicy
  def create_label?
    project.user == user
  end
end
...

policy(@project).create_label?
```

**Comment by jnicklas** [comment]
I agree with @scottjacobsen, I would go with option A if possible. There are cases where I've done something like option B, but I try to avoid it if I can.
