### ISSUE TITLE
Configurable policy class inference suffix (e.g. ModelPolicy -> ModelPermissions)

### ISSUE THREAD

**Issue by nruth** [elabs/pundit#233]
We're using pundit with great success (thanks!), but I've run into a naming conflict with factoring out [policy objects](http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/). 

I'd like to rename our pundit policy files rather than change the convention suggested in the article. I'd prefer not to hard-code all the policy class names.

It looks like modifying https://github.com/elabs/pundit/blob/master/lib/pundit/policy_finder.rb#L50 would achieve alternative prefixes, but I wondered whether the creators would accept this as a PR, or can think of other things it might break?

**Comment by jnicklas** [comment]
I'm :-1: on this. Actually, Pundit is pretty much modelled on the blog post you linked. That post and @jamesgolick's (RIP) objectify where the main source of inspiration for this library. So I'd rather say that it isn't a clash at all ;) If we do support this, the generators would become pretty strange, imo.

**Comment by jnicklas** [comment]
I've gone with a middle-ground solution on this, by extracting the suffix into a constant, rather than a configuration option. This way you can override the constant for your use-case, but that's not an officially supported feature, and there's no weirdness with the generators.

**Comment by nruth** [comment]
Thanks, I'll try it out.
