### ISSUE TITLE
Best way to use policies in a Javascript app?

### ISSUE THREAD

**Issue by volkanunsal** [elabs/pundit#238]
I am planning to switch several Rails views into a JS app. These views have policy checks like this:

```haml
-if policy(project).edit?
  =link_to 'Edit', edit_project_path
```

I imagine you could compile the Policy into a JS class. Is there a simpler alternative to doing this?

**Comment by rosswilson** [comment]
What I do is set ```data-``` attributes on the HTML ```body``` tag to indicate permissions. e.g

```<body data-can-edit="true" data-can-delete="false">```

You could use ```content_for``` within each Rails view to set these attributes on the body tag within ```application.html.erb```

**Comment by thomasklemm** [comment]
When pre-rendering views without access to the actual `@project`, you'll need to pass the information to the JS code that's rendering the view in the browser. There are several strategies for passing data to JS, providing it via `data`-tags or via [gon](https://github.com/gazay/gon) being common ones. [This RailsCast](http://railscasts.com/episodes/324-passing-data-to-javascript) might be worth a look.

**Comment by markalanevans** [comment]
Is it possible to get a list / array of the allowed policies of a user. 

ex: 
```
["user post", "delete user", "create admins", ...]
```

If so you can, then for example as an AngularJS user developer, you might:
Have a controller action method returns the polices for a user.


In JS  call the API, return an array of Allowed policies.
["user post", "delete user", "create admins", ...]

Then A simple directive    can-do="user posts"  could have logic behind it like 

```coffeescript

policies = p["user post", "delete user", "create admins", ...]
if "user post" in polices
   return true
else
   return false
```


Is there such a helper method to get a list of allowed policies?

**Comment by jnicklas** [comment]
The only way you could get this kind of list is through meta-programming or reflection in your policies. however, Pundit explicitly does not in any way dictate the design of your policies, so this kind of thing is outside the scope of Pundit.
