### ISSUE TITLE
Accept parameter in policy method

### ISSUE THREAD

**Issue by Canifex** [elabs/pundit#239]
Given I want to create an project manager with a to do list. Each item on the to do list belongs to one project, one project has many members, but -of course- you can only assign a task to a specific member, if this member is in the same project. So I need to check:
1) is the current user in the project
2) in the target assignee in the project
Ideally, my policy should look like this:

```ruby
class TaskPolicy < EventDependentPolicy
  def update?
    user_particiaptes?
  end

  def assign?(wanted_assignee)
    user_participates? && record.project.members.include?(wanted_assignee)
  end

  def user_participates?
    record.project.members.include?(user)
  end
end
```

So I need the wanted_assignee variable, but only for this use case.. How should I do that as a best practice?

**Comment by jnicklas** [comment]
I actually often add these kinds of checks as validations on the model, since you can think of them as relating to data-coherence rather than authorization. There is no circumstance where a user should ever be assigned to a task for a project where they're not a member, that won't ever change due to permissions.

**Comment by zoot123** [comment]
I have a similar problem. I would like to check if the current_user is like a passed user. I know there is a way to do this with additional context but I think that is much work for this "easy" check.
Is there any simple way to pass parameters?
something like this

Controller:
def destroy_abo
  authorize @broadcast, @current_user, @user
  ...
end

Policy
def destroy_abo?
  return true if (current_user.id == user.id)
end
