### ISSUE TITLE
Multiple policies per model

### ISSUE THREAD

**Issue by volkanunsal** [elabs/pundit#241]
I have a user model with several controllers that have slightly different configurations. I have a `User::InvitationsController` and `User::RegistrationsController`, so I figured I should have a `UserInvitationPolicy` and a `UserRegistrationPolicy`. But I find this hard to work with when I call 

```ruby
authorize(resource)
```

I could use

```ruby
UserRegistrationPolicy.new(current_user,resource).create?
```

But this requires me to bypass the controller actions that verify whether an authorize has been run. Is there a better solution for this use case?

**Comment by jnicklas** [comment]
Currently, policies are heavily tied to models, and not so much to controllers. One option you do have is to create a virtual `Invitation` model, often this makes sense, but sometimes it does not, in which case there isn't really a clean solution with Pundit as it stands. We currently don't have any way of overriding the policy for a particular controller though.

**Comment by valscion** [comment]
What we're using in a similar case is the version of `authorize` which doesn't require a model to be passed as the first object, but infers the name of the policy from a symbol.

Let's say I have some sort of a dashboard where one action is `manage_posts`. When I want to check whether the current user is authorized to run those things, I use policy similar to this:

```ruby
class DashboardPolicy < Struct.new(:user, :dashboard)
  def manage_posts?
    user.admin? || user.moderator?
  end
end
```

And querying the authorization capabilites happens by running

```ruby
authorize :dashboard
```

If my action name wouldn't map to the `manage_posts?` method, I'd simply pass it as a second variable.

What are you trying to achieve? Do you want to test whether the current user is authorized to do something to some other specific resource (e.g. update a `Post` object which belongs to the `User`)? Or do you want to just authorize whether the user is able to do some specific action?

**Comment by Sonna** [comment]
@volkanunsal, based of @jnicklas suggestion of creating a virtual model, perhaps you could something like a form object that contains the User `resource`, create the appropriate form object (e.g. `RegistrationForm`) within the `RegistrationController`, then pass it the new User `resource` you are trying to create and `authorize`; like in the following:

```ruby
# app/forms/user/registration_form.rb
module User
  class RegistrationForm
    attr_reader :resource

    def initialize(resource)
      @resource = resource
    end
  end
end

# app/controllers/user/registrations_controller.rb
module User
  class RegistrationsController < ApplicationController
    def create
      resource = User.new
      registration_form = RegistrationForm.new(resource)
      authorize(registration_form)
      # etc
    end
  end
end

# app/policies/user/registration_form_policy
module User
  class RegistrationFormPolicy
    attr_reader :user, :form

    def initialize(user, form)
      @user = user
      @form = from
    end

    def create?
      user != form.resource # or some other authorization
    end
  end
end
```
Then the `RegistrationForm` can be extend to include any additional validation required during User sign up, but needed on the User model, or whatever you decide.

**References:**
- [Railscasts # 416 Form Objects](http://railscasts.com/episodes/416-form-objects)

**Comment by jnicklas** [comment]
I don't think this issue is leading to anything concrete. I'm closing this for now.

**Comment by eavonius** [comment]
I agree this issue isn't trivial and needs a solution. I have multiple controllers that use the user for instance one that index/show/edit/update the user itself and one that does the same for a user's avatar. Both controllers need a policy for user but it tries to use UserPolicy for both.

I've used the workaround suggested here, remove verify_authorized from the controller and add:

if not AvatarPolicy.new(current_user, @user).upload?
  raise Pundit::NotAuthorizedError
end

where AvatarPolicy is my "other" user policy. I don't see why the devs don't want to add an option to pass the policy in explicitly. There is architectural purity, and then there is pragmatism. It's not like it hurts the API to allow passing :policy for these cases and use it as is if not.

My two cents.

**Comment by cstump** [comment]
I found this thread when dealing with the same problem. I have a `Shop` model that is managed by a `ShopsController` using `ShopPolicy`, and I have a `HostsController` that manages `Shop` instances in a different manner. Naturally, I want to use a `HostPolicy` from `HostsController`, but when I first tried Pundit insisted on using `ShopPolicy`. So I made a wrapper class named `Host` that behaves just like a `Shop`.
```
class Host < SimpleDelegator
  def self.policy_class
    HostPolicy
  end
end
```
I authorize in `HostsController` with `authorize Host.new(shop)`. Inside `HostPolicy` I can treat `record` just like a `Shop` object.

Works for me! Hope that helps.

**Comment by hundsim** [comment]
A quite common pattern, or at least [recommended by DHH](http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/) is to have many more controllers than models. "So, in Basecamp 3 we spin off controllers every single time there’s even sort of a subresource that makes sense."

As Pundit appearantly isn't made for this kind of structure, any suggestions of alternative authorization tools?

**Comment by kaleb4eg** [comment]
We have faced with same problem on our project - we have few controllers and only one policy.

**Comment by duykhanh21** [comment]
I ran into same problem when I have some controllers which manage separate attributes of a group.
Combine these controllers into one seems to be painful while only one policy can not take them all.

**Comment by ce07c3** [comment]
The more complex resolution becomes, the less sense it makes to it automatically. Why don't you specify the policy explicitly?

Another idea is to extend Pundit's resolution algorithm to fit your needs, e.g. by supplying custom resolution strategies to it. :)

**Comment by NoNonsense126** [comment]
One of the way to deal with this would be to namespace the policy. For example, if I had a `HostsController` with a `@shop` instance variable

Create a policy at /app/policies/hosts/shop_policy.rb

`
class Hosts::ShopPolicy
  def initialize(user, resource)
    @user = user
    @shop = resource.last
  end

  def show?
    // authorize here
  end
end
`

`
class HostsController < ApplicationController
  // other code

  def show
    @shop = Shop.find(params[:id])
    authorize [:hosts, @shop]
  end
end
`

**Comment by MyklClason** [comment]
I'll be testing this out later, but seems like generalized nested policies would work here via the directory structure and inheritance.

```
/app
  /policies
    /post
      admin_policy.rb | class Post::AdminPolicy < AdminPolicy
      moderator_policy.rb | class Post::ModeratorPolicy < ModeratorPolicy
      user_policy.rb | class Post::UserPolicy < UserPolicy
  /post_policy.rb
  /admin_policy.rb
  /moderator_policy.rb
  /user_policy.rb
```

```
class NestedPolicy < ApplicationPolicy
  def policy_folder_path
    '/application'
  end

  ...

  def get_policy_class_names
  # 1. Fetch all the files from policy_folder_path that end with `_policy.rb`
  # 2. Convert those filenames into class names.
  end

  def index?
    policy_names = get_policy_class_names # implement get_policy_names
    # Yry each one to see if any policies allow you to do this.
    return policy_names.any? { |p| p.new(current_user, record).send(__method___) }

   # in this example it effectively does:
   #   Post::AdminPolicy.new(post).index? 
   #   || Post::ModeratorPolicy.new(post).index?
   #   || Post::UserPolicy.new(post).index? 
  end

 ...
end
```



With that, multiple polices can be handled via:

```
class PostPolicy< NestedPolicy
  def policy_folder_path
    'posts'
  end
  ...
 ...
end
```

**Comment by MyklClason** [comment]
> @MyklClason did you mean for each `app/*_policy.rb` to define `class Post::UserPolicy` in your example or was it perhaps a copy-paste error?

That was indeed a copy/paste error. I corrected it and added Thread as another example.

**Comment by andrew-oko-odion** [comment]
> I have a user model with several controllers that have slightly different configurations. I have a `User::InvitationsController` and `User::RegistrationsController`, so I figured I should have a `UserInvitationPolicy` and a `UserRegistrationPolicy`. But I find this hard to work with when I call
> 
> ```ruby
> authorize(resource)
> ```
> 
> I could use
> 
> ```ruby
> UserRegistrationPolicy.new(current_user,resource).create?
> ```
> 
> But this requires me to bypass the controller actions that verify whether an authorize has been run. Is there a better solution for this use case?

this is exactly my use case... 
how did you eventually resolve this

**Comment by MyklClason** [comment]
@andrew-oko-odion Sadly I can't locate the project I used this on, but I believe this is what you seek:

https://github.com/varvet/pundit#policy-namespacing

```
  def authorize(record, query = nil)
    super([:user, resource], query)
  end
```

**Comment by andrew-oko-odion** [comment]
Thanks would test it out
