### ISSUE TITLE
How is context used in the policy?

### ISSUE THREAD

**Issue by hoguej** [elabs/pundit#242]
In this section of the documentation, it would be nice to show how the additional context is accessed from the policy.

https://github.com/elabs/pundit#additional-context

Is this object simply placed into @user?

So, if I create this context class:

``` ruby
class UserContext
  def initialize(user, context)
    @user = user
    @context = context
  end
end
```
then do 
``` ruby
def pundit_user
 UserContext.new(current_user, context)
end
```
Do I now access the user and context within the policy by doing?:
``` ruby
user.user
user.context
```

**Comment by thomasklemm** [comment]
I guess that's actually a good way to pass additional information into your policies. Let us know how it works out for you.

**Comment by jnicklas** [comment]
@hoguej yes, that's how it's meant to be used. And yes, it's all just Ruby :)
