### ISSUE TITLE
Has many through association question

### ISSUE THREAD

**Issue by schristm** [elabs/pundit#243]
So, we've got an app where a user may have admin level access to all clients across the entire system, or they may be limited with access to just a few clients.

Users that have this admin-level access, have an association called Permission that contains boolean fields like can_access_billing and can_do_whatever. These are system-wide permissions.

The users that have client-level access are granted permission via a join table, called memberships. A membership record belongs to a client, a user, and has a roles mask for different permissions.

What I'm trying to figure out with Pundit, is how to check if, for example, a user has billing permission on a particular client. Usually, you'd check @membership.role?(:billing). I'm not seeing how to pass the membership to the InvoicePolicy, however, or how to access this cleanly, without having to do something like:

```ruby
@membership = user.memberships.find_by(client_id: record.client_id)
@membership.role? :billing
```

Any advice would be appreciated. I'm excited to be switching our code base over from cancan to pundit, and appreciate your contribution to open source.

**Comment by darylprickett** [comment]
If I understand your question correctly, you could create a method on your user model to determine if the user has the role for the given client. 

def has_role?(role_name, client_id)
---your logic here
end

and in your policy

def some_action?
  user.has_role?(:billing, record)
end

At least by putting the logic to determine if the user has the role in a single location you fix the demeter violation "user.memberships.find_by(etc etc" and have a testable chunk of code. Then using that function in your policy should help make the policy a bit easier to understand.

**Comment by jnicklas** [comment]
What's wrong with the example you posted?

``` ruby
@membership = user.memberships.find_by(client_id: record.client_id)
@membership.role? :billing
```

That seems pretty sane to me?
