### ISSUE TITLE
before_policy callback feature request

### ISSUE THREAD

**Issue by passion8** [elabs/pundit#244]
I think every class policy (`PostPolicy` , `CommentPolicy` )  have some high level  restrictions like user can't edit the post if he is not online. Putting this logic in every policies (`update?` , `create?`) doesn't seem to be good idea, thinking to extract it into some callback something like 

     class PostPolicy < ApplicationPolicy
       before_policy :must_be_online_user
        
       private
         def must_be_online_user
            user.present?
         end
          
    end

What you think ?

Basically, this is what i am saying technically  but want this `callback` functionality as feature or if you have some better idea ...please let me know. Or what is the best practice to handle such type of repeating restriction conditions?

    class PostPolicy < ApplicationPolicy
     
      include ActiveSupport::Callbacks
      define_callbacks :update   , terminator: ->(target, result) { result == false }
      set_callback :update , :before , :must_be_signed_in
     
     def update?
        run_callback :update do
           // my logic
        end
     end
    
      private
        def must_be_signed_in
          user.present?
        end

    end

**Comment by passion8** [comment]
i have developed this functionality.


    // lib/before_policy.rb
    module BeforePolicy
    
      def method_added(meth)
        return if meth == @method_to_run
        return if @recursing
        @recursing = true
        old_method = instance_method meth 
        method_to_run = @method_to_run
        define_method meth do
          if send (method_to_run)
            old_method.bind(self).call
          end
        end
        @recursing = nil
      end
    
      def before_policy methods_to_run
        @method_to_run  = methods_to_run
      end
    
    end

And this is the usecase


    require 'before_policy'
    class AnswerPolicy < ApplicationPolicy
      extend BeforePolicy
      before_policy  :must_be_signed_in 
      
      def edit?
         user.karma > record.user.karma
      end

      private    
        def must_be_signed_in
          user.present?
        end
    end

**Comment by passion8** [comment]
Let me know if you want this functionality in pundit, i will push it.

**Comment by thomasklemm** [comment]
Seems like you're trying to make your app a closed system only accessible to registered users. Please take a look at [this suggestion](https://github.com/elabs/pundit#closed-systems) in our Readme.

**Comment by jnicklas** [comment]
Agree with @thomasklemm.

It's been a policy (heh) in Pundit that we don't have any functionality in the gem itself which adds anything to policy classes. Policy classes are meant to be completely implemented and controller by the user, and completely outside the control of Pundit.
