### ISSUE TITLE
Using Pundit with this API structure

### ISSUE THREAD

**Issue by dmateos** [elabs/pundit#245]
I recently implemented a json api as per this article:

https://codelation.com/blog/rails-restful-api-just-add-water

When i try to use pundit with this im getting

     Pundit::NotDefinedError:
       unable to find policy NilClassPolicy for
     # /Users/dm/.rvm/gems/ruby-2.1.0/gems/pundit-0.3.0/lib/pundit/policy_finder.rb:28:in `policy!'

**Comment by thomasklemm** [comment]
The exception message suggests that you're trying to do `authorize nil`, since your instance variable is `nil` for some reason. This error is not related to pundit. If you have further questions on how to debug your code, you could post it to StackOverflow.
