### ISSUE TITLE
Rails 4 rspec verify_partial_doubles causes error

### ISSUE THREAD

**Issue by rosswilson** [elabs/pundit#246]
In my Rspec view tests I am mocking the policy object like the Pundit README suggests:

```allow(view).to receive(:policy).and_return double(new?: true)```

But in a new Rails 4 app with Rspec ```mocks.verify_partial_doubles``` has been changed to default to true. This causes failing tests with the error:

```does not implement: policy```

Setting  ```mocks.verify_partial_doubles = false``` in spec_helper.rb fixes this issue.

Is this something that can be resolved in pundit? Or can I mock my ```policy``` method calls in a different way?

**Comment by rosswilson** [comment]
Further research points to this rspec issue being related: https://github.com/rspec/rspec-mocks/issues/633

**Comment by thomasklemm** [comment]
This issue doesn't seem to be related to `pundit`, but rather a result of how RSpec 3 handles the stubbing of controller methods. You could give the suggested workarounds in https://github.com/rspec/rspec-rails/issues/1076 a try.
