### ISSUE TITLE
Pundit policies with two input parameters

### ISSUE THREAD

**Issue by Rowandish** [elabs/pundit#248]
I'd like to compare two objects: `@record` and `@foo`, as you can see here:

    class BarPolicy < ApplicationPolicy
      def show?
        @record.foo_id == @foo
      end
    end

I don't reach to find a good way to pass a second parameter to pundit methods (@foo).

I'd like to do something like:

    class BarsController < ApplicationController
      def test
        authorize bar, @foo, :show? # Throws ArgumentError
        ...
      end
    end

But the Pundit authorize method allows only two parameters.
Is there a workaround for this?

Thanks!

**Comment by zeeraw** [comment]
Take a look at https://github.com/elabs/pundit#additional-context where you could leverage the same technique for composite records.

**Comment by Rowandish** [comment]
@zeeraw Oh I didn't look at the readme well. I solve, thanks
