### ISSUE TITLE
Best way to child models for `accepts_nested_attributes_for`

### ISSUE THREAD

**Issue by jecornwall** [elabs/pundit#249]
I have a model:
`
class User < ActiveRecord::Base
  has_many :roles
  accepts_nested_attributes_for :roles, allow_destroy: true
end
`

I then have a User form that includes a list of Roles. The form allows you to create, update and destroy these roles. If you're unfamiliar with `accepts_nested_attributes_for` it means the attributes come into the controller like this:
`
      params[:user].permit(:name, 
                           :email, 
                           roles_attributes: [:title, 
                                              :id, 
                                              :_destroy)
`

With Rails adding a `roles_attributes=` method to the User model that takes care of the tricky bits of creating, updating and destroying. 

My question is: what would be the best way to insert a RolePolicy into this pipeline? Ideally I'd like something on the controller, but the only way I can currently think of is to use the `:reject_if` option on `accepts_nested_attributes_for` (See http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#method-i-accepts_nested_attributes_for).

**Comment by jnicklas** [comment]
I think the only sane way is to authorize after assigning attributes. So something like:

``` ruby
@user = User.new(params[:user])
authorize(@user)
@user.roles.each { |role| authorize(role) }
```

Make sure to set the `inverse_of` attribute like this:

``` ruby
class User
  has_many :roles, inverse_of: :user
  ...
```

Otherwise this probably won't work, since you won't know which user the roles belong to before they're persisted.
