### ISSUE TITLE
Tests fail on latest `activesupport`

### ISSUE THREAD

**Issue by ecbypi** [elabs/pundit#252]
`ActiveSupport` v4.2.0 deprecated `Kernel#capture` and uses `ActiveSupport::Deprecation` to notify the user.  Since spec_helper.rb doesn't require "active_support" to setup autoloading, or "active_support/deprecation" directly, this causes the call to `capture` to [fail][].  

Adding `require "active_support"` or `require "active_support/deprecation"` fixes the problem, but since `capture` is deprecated, I was wondering how to best update the code in `spec_helper` so RSpec's deprecation warnings are caught without using the deprecated `capture`.  Any thoughts on borrowing the implementation of `Kernel#capture` into `spec_helper`?  `capture` was deprecated because it isn't thread-safe.  In the context where it's used in spec_helper.rb, this doesn't seem to be an issue.  

[fail]: https://travis-ci.org/elabs/pundit/jobs/51556714

**Comment by thomasklemm** [comment]
I'm good with borrowing the `Kernel#capture` implementation from `ActiveSupport` for our `spec_helper`. Would you like to open a PR?

**Comment by ecbypi** [comment]
Gladly!
