### ISSUE TITLE
Possibility to list resources user is allowed to access

### ISSUE THREAD

**Issue by giedriusr** [elabs/pundit#255]
For instance, we have:

```ruby
# models
Post
Comments
Users
```

```ruby
# roles
admin
moderator
reporter
```
```ruby
# policies
UserPolicy
PostPolicy
CommentPolicy
```
`current_user - admin` would have access to all resources, `moderator` - posts, `reporter` - comments only.
Listing user resources would be useful. What others think?

**Comment by darylprickett** [comment]
I did something similar in my application but I just coded it in the policy. 

def admin?
   user.role == 'admin'
end

def moderator?
  user.role == 'moderator'
end

def some_admin_only_action?
  admin?
end

def some_moderator_function?
  admin? || moderator?
end

Hopefully that gets the idea across. Some of the functions I defined in the application policy so they can be accessed from any policy.

**Comment by giedriusr** [comment]
No, my goal was to have smth like this:

```ruby
def available_resources
    if super_admin?
      return %w(users roles)
    elsif ops_admin? || marketing_admin? || support_user?
      return %w(comments posts)
    end

    []
end
# then I would call 
current_user.available_resources 
# and it would list accessible resources for this user
```

**Comment by darylprickett** [comment]
It sounds like you will have your business logic of authorization maintained in two places. The method you are talking about building plus Pundit determining if a specific controller request is allowed or not. If you are looking for a way to return the resources, via model method, and authorize them all at once I don't think Pundit will work for you.

**Comment by giedriusr** [comment]
Ok, thank you! :-)
