### ISSUE TITLE
How to write a scope policy for an index action that already scopes models to a current user.

### ISSUE THREAD

**Issue by abitdodgy** [elabs/pundit#257]
I'm wondering, how do we use Pundit in situations like below.

In this example I have `workspaces#index` action where I'm loading workspaces that the current user is a member of:

```ruby
class WorkspacesController < ApplicationController
  def index
    @workspaces = current_user.workspaces
  end
end
```

This assumes a `User` with a `has_many :workspaces, through: :memberships` relation. What would the index method look like in a Pundit policy using `policy_scope`?

**Comment by abitdodgy** [comment]
It looks like authorization isn't even necessary in this scenario, but it would be nice to have everything go through pundit instead of picking and choosing actions, which could lead to mistakes.

**Comment by ecbypi** [comment]
@abitdodgy.  You can put the `current_user` filtering into the policy scope.

```ruby
class WorkSpacesPolicy
  class Scope < Struct(:user, :scope)
    def resolve
      user.workspaces
    end
  end
end
```

**Comment by abitdodgy** [comment]
@ecbypi cheers. That solves it, with a minor modification:

```ruby
  class Scope < Scope
    def resolve
      user.workspaces
    end
  end
```
