### ISSUE TITLE
Question about double authorization on updates

### ISSUE THREAD

**Issue by uberllama** [elabs/pundit#265]
Lets assume this scenario:

* A post has two statuses: `draft`, and `posted`.
* Only `draft` posts can be updated.
* A post can optionally belong to a group.
* Users have conditional access to groups.

```ruby
class PostsController < ApplicationController
  before_action :load_post

  def update
    authorize @post
    @post.update(post_params)
  end

  def post_params
    params.require(:post).permit(:body, :status, :group_id)
  end
end

class PostPolicy

  def create?
    record.group_id.nil? || user.groups.where(id: record.group_id).exists?
  end

  def update?
    record.draft? && (record.group_id.nil? || user.groups.where(id: record.group_id).exists?)
  end
end
```

We have to authorize `@post` prior to the update, in order to ensure its a draft. But because `group_id` is a permitted param, it could be changed on update and that change wouldn't be authorized.

This is a very common scenario. I've handled it in various ways, none of which feel great, and was curious what you folks are doing. Cheers.

**Comment by jnicklas** [comment]
I've also run into this a couple of time. I usually add a method to application controller which authorizes both before and after, something like:

``` ruby
def update_attributes(record, attributes = {})
  authorize(record)
  record.assign_attributes(attributes)
  authorize(record)
  record.save
end
```

It's a bit weird, but it's the least insane solution I've come up with. Check out #263 where I've added a method like this to Pundit itself, but I'm not sure if that's a great idea, so it remains unmerged for now.

**Comment by uberllama** [comment]
Thanks for the reply Jonas. My opinion in this case would be that your reservations are warranted on not merging that PR. I use a lot of service/workflow objects for updates so I couldn't use the new helper anyway. Its good to get validation on the double authorize though. Cheers.

**Comment by uberllama** [comment]
Actually, just as I hit submit on that, I realized the double authorize won't work in this case, because the Post will be `posted` once the attributes are assigned.

**Comment by ecbypi** [comment]
@uberllama, you can wrap the `assign_attributes` and the second call to `authorize` in a transaction so it will be rolled back if there is an authorization failure.

**Comment by uberllama** [comment]
I think the only way a double authorize would work in this case is if you were specifically checking pre-change values:

```ruby
def update?
  record.status_was == "draft" && (record.group_id.nil? || user.groups.where(id: record.group_id).exists?)
end
```

It may just be that the code is as complex/weird as the specific use case warrants.

**Comment by jnicklas** [comment]
@uberllama `assign_attributes` does not persist the record, so there's no need to wrap that in a transaction. The changes will be persisted after the second `authorize` when we call `save`.

**Comment by uberllama** [comment]
Yeah, @ecbypi had mentioned transactions, not me. My issue was that the assigning of the attributes would cause the second authorize to fail unless you use `_was` in the event that that attribute changes.

**Comment by ecbypi** [comment]
@uberllama, my bad.  I thought you meant assigning attributes was still causing a database change (either through an association change or customized writer on the model).

**Comment by jnicklas** [comment]
I think this discussion is concluded, so I'm closing this.
