### ISSUE TITLE
Why namespaces got reverted?

### ISSUE THREAD

**Issue by spieker** [elabs/pundit#271]
I currently use Pundit in a project and need namespaces in order to support a legacy API. I have seen in the commits, that namespaces got reverted on the 22. of August 2014. What was the reason for this? Is there anything planed to include them again?

**Comment by jnicklas** [comment]
Please find the relevant issue and read it.

**Comment by spieker** [comment]
Thank you for the info. If anyone still needs namespaces for pundit, I have created a concern doing it. It only works for the master version of pundit.

Have fun: https://gist.github.com/spieker/7ca47826967c8b584f80
