### ISSUE TITLE
Multiple Scopes and nested collections 

### ISSUE THREAD

**Issue by ts-silvio** [elabs/pundit#272]
I don't know how to best use Pundit Scopes for my needs so I would like to explain my use case and hope to get some feedback if I'm completely off the right path or what I do is reasonable.

The system is a Json API. 

I have Users, Users can be friends with other users. Users have Notes. They can be private, visible to friends or public.
There are also Groups. Notes can belong to groups and are visible to all members of that group.

I want to return different collections of the same nested resource (Notes) on different API endpoints.

``` ruby
users/:id/notes # all notes for a specific user
users/friend_notes # all notes of the current users friends
```

### 1st endpoint with scope
For the first endpoint I had to jump through some hopes but got it working like this:

I want to fetch the Notes for an User, I need to know if it's
* for the current user (then include private, friend-visible and public notes),
* a friend of the current user (include friend-visible and public notes and notes in Groups where both Users are members) or
* a user who isn't a friend of the current user (only return public notes and Notes from Groups where both users are members).

So what I do is include the requested User alongside the current user in a [UserContext Object](https://github.com/elabs/pundit#additional-context), so I can determine their relation in the policy.
```ruby
class ApplicationController < ActionController::API
  include Pundit
  after_action :verify_authorized

  class UserContext
    attr_reader :current_user, :requested_user

    def initialize(current_user, requested_user = nil)
      @current_user = current_user
      @requested_user = requested_user
    end
  end

  def pundit_user
    if params[:user_id].present?
      requested_user = User.find(params[:user_id])
      UserContext.new(current_user, requested_user)
    else
      UserContext.new(current_user)
    end
  end
end
```

Because I feel this should use a scope in the NotesPolicy I pass in a symbol to direct it there. I can't pass in a collection of all Notes the User has because of the different types that GroupNotes and StandardNotes have. I haven't yet tested if the pattern shown [here](https://github.com/elabs/pundit/issues/235#issuecomment-67665840) would be useful for me.

```ruby
module V1
  class UsersController < ApplicationController
    skip_after_action :verify_authorized, only: :notes
    after_action :verify_policy_scoped, only: :notes

    def notes
      @notes = policy_scope(:note)
      render "v1/notes/index"
    end
  end
end

class NotePolicy < ApplicationPolicy
  class Scope < Scope
    attr_reader :current_user, :requested_user

    def initialize(user, _scope)
      @current_user = user.current_user
      @requested_user = user.requested_user
    end

    def resolve
      if current_user == requested_user
        current_user.all_notes
      elsif current_user.friend_with? requested_user
        requested_user.std_notes.friend_visible + 
          requested_user.std_notes.public_visible +
          requested_user.shared_group_notes(current_user)
      else
        requested_user.std_notes.public_visible + requested_user.shared_group_notes(current_user)
      end
    end
  end
end
```

### 2nd endpoint with scope

It's getting ugly for the second scope for the same resource. Because the ``UserContext`` is also used, even though I don't need it, and I have to use another name for the Scope method because 'resolve' is already used for the other collection, my call looks like this:
```ruby
module V1
  class UsersController < ApplicationController
    skip_before_action :authenticate_user_from_token!,
                       only: [:create, :signin, :reset_password]
    skip_after_action :verify_authorized, only: :notes
    after_action :verify_policy_scoped, only: :notes

    def notes_from_friends
      authorize :user

      ctx = UserContext.new(current_user, nil)
      @notes = NotePolicy::Scope.new(ctx, :note).friend_notes

      render "v1/notes/index"
    end
  end
end

# with a Policy Scope like this:

class NotePolicy < ApplicationPolicy
  class Scope < Scope
    attr_reader :current_user, :requested_user
    def initialize(user, _scope) ... end
    def resolve ... end

    def friend_notes
      notes = []
      current_user.friends.each do |friend|
        notes.push(*friend.std_notes.friend_visible)
        notes.push(*friend.std_notes.public_visible)
      end
      notes
    end
  end
  # ...other stuff
end
```
Another issue is, calling the custom method in the controller doesn't seem to verify that the method was authorized, so I can't use the ``verify_policy_scoped`` callback. That's why I have an additional ``authorize :user`` in here.

**Comment by jnicklas** [comment]
Please summarize your point. I don't have time to read and understand so much code, sorry.

**Comment by ts-silvio** [comment]
Thank you for your answer. I see, sorry for spaming you. I thought it would be helpful to include the code examples.
My problem is I couldn't figure out how to implement scopes for multiple collections of the same resource when I also need additional context. Maybe my use case is too specific, will close this.

**Comment by ts-silvio** [comment]
By re-reading my issue I think it would have been completely understandable by just reading the text and ignoring the code.
