### ISSUE TITLE
pundit gem out of date on rubygems

### ISSUE THREAD

**Issue by ericraio** [elabs/pundit#273]
there was some code I was referencing here that I wanted to use, the pundit/version says this codebase is 0.3.0 but the version has been out of date since August and the rubygems has been out of date.

**Comment by darryn02** [comment]
+1

**Comment by felixtriller** [comment]
+1

**Comment by jnicklas** [comment]
I just release Pundit 1.0.0 to Rubygems. :tada: :balloon: :cake:
