### ISSUE TITLE
Allow to customize current_user helper

### ISSUE THREAD

**Issue by sungwoncho** [elabs/pundit#274]
Currently, Pundit assumes that there is `current_user` method available in the app. I'd like to suggest that we allow to customize this method, as someone might be using a resource named differently from `user`.

I think this can be achieved by generating an initializer file, and changing `#pundit_user` in lib to read from that initializer file. Any thoughts?

**Comment by jnicklas** [comment]
I don't understand how this is different from `pundit_user`. We added it specifically so the user object passed to pundit could be customized, doesn't that do the exact thing you want?

**Comment by sungwoncho** [comment]
Yep. Modifying `pundit_user` does the same thing. Yet it requires users to go through the hassle of forking the repo, and using the forked version.

**Comment by sungwoncho** [comment]
Yep. It does the same thing.
