### ISSUE TITLE
How can I pass an extra argument into a headless policy?

### ISSUE THREAD

**Issue by brandoncc** [elabs/pundit#275]
I have this policy

```ruby
class ProductManagementPolicy < Struct.new(:user, :product_management, :store)
  def index?
    store.account == user
  end
end
```

I was hoping that it would allow me to do this but it won't.

Here is my spec:

```ruby
describe ProductManagementPolicy do
  subject { described_class }
    
  permissions :index? do
    it 'permits store owner' do
      product = Fabricate(:product)
      expect(subject).to permit(product.store.account, :product_management, product.store)
    end
  end
end
```
I don't want to use `index?` on the store policy, because that has nothing to do with this controller. This index action handles displaying products in a management dashboard. How can I use a policy that is not based on `Store`, but pass a store into it? I need it to work with the `authorize` method. I was thinking I could create a domain object which contains the store and the user, then validate on that, but it seems like there should be a better way.

**Comment by deefour** [comment]
What you're trying to do *(pass params other than the current user and record being authorized)* is a very common request. It usually means you're going about your authorization the wrong way.

In your case, I'd wonder if you'd benefit from simply having the following method on your `StorePolicy`

```ruby
def manage_products?
  record.account == user
end
```

but even then *(not knowing the details of your project)*, I'd also wonder if having a `manage?` method on your `Product` class would be even more appropriate.

For the rare cases you do need to pass additional data to the policy, the [README explains a solution](https://github.com/elabs/pundit#additional-context).

**Comment by brandoncc** [comment]
I knew I had read that information about passing additional information, I just couldn't figure out where. Thank you for your response. Your ideas make total sense, I think a manage? method will work for me. Thank you again for your fast response!

**Comment by vedmant** [comment]
What's the point to write so much code with user context just to pass a param to a single policy method when no other methods need this. In my case only create? method needs additional param almost on any policy I use. I just need to check it against a parent model if it belongs to current user.

**Comment by Linuus** [comment]
@vedmant Please don't comment on _every_ issue about additional arguments. One is enough.
