### ISSUE TITLE
Upgrade guide to 1.0?

### ISSUE THREAD

**Issue by acrogenesis** [elabs/pundit#278]
I'm running pundit 0.3 with Rails 4.2.1, Ruby 2.2.2.

Are there any special considerations I have to take while upgrading to this major release

**Comment by jnicklas** [comment]
See the Changelog for a list of changes. https://github.com/elabs/pundit/blob/master/CHANGELOG.md

I think there isn't anything majorly breaking in there. I'm unsure if anyone has written a guide, but I doubt it. It should be fairly straight-forward to upgrade.

Let us know if you run into any problems.
