### ISSUE TITLE
unable to find 'BetumPolicy' for ':beta'

### ISSUE THREAD

**Issue by jasonl99** [elabs/pundit#280]
I must be missing something.  I modeled this after the DashboardPolicy example:

```ruby
class BetaPolicy < Struct.new(:user, :beta)
  def has_access?
    # determine access, return true or false
  end
end
```
When I do 
```ruby
authorize :beta, :has_access?
```

I get the following error:

```code
Pundit::NotDefinedError: unable to find policy `BetumPolicy` for `:beta`
from /home/jason/.rvm/gems/ruby-2.2.2/gems/pundit-1.0.0/lib/pundit/policy_finder.rb:30:in `policy!'
```

If I try calling
```ruby
authorize :betas, :has_access?
```
it works.   I imagine this has something to do with rails' thinking that beta is plural, and it's trying to singularize it, but I don't have a Beta or Betam table in the system.   Incidentally, using the DashboardPolicy example worked just fine.

**Comment by deefour** [comment]
The Pundit policy finder uses `classify` under the hood. From the [Rails API docs](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-classify)

> Create a class name from a plural table name like Rails does for table names to models

Compare single/plural `:dashboard` to `:beta`

```
[7] pry(main)> :dashboard.to_s.classify
=> "Dashboard"
[8] pry(main)> :dashboards.to_s.classify
=> "Dashboard"
[9] pry(main)> :beta.to_s.classify
=> "Betum"
[10] pry(main)> :betas.to_s.classify
=> "Beta"
```

IMO, this should be considered a bug. When you're passing a symbol, it's to find a policy not bound to a table-based model.

**Comment by jasonl99** [comment]
Thanks..I had just started looking into it myself and came to the same conclusion with classify.  Perhaps the better thing would be to use object.to_s.titleize.remove(' ')  I know there's a rails function in there somewhere which will do it with one method, though

**Comment by jnicklas** [comment]
I think you are going about this the wrong way. The Rails inflector isn't pluralizing "beta" correctly, but instead of fixing *that* you're throwing out the baby with the bathwater.

``` ruby
"beta".classify # => "Betum"
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular "beta", "betas"
end
"beta".classify # => "Beta"
```

I think Pundit is doing the right thing by using `classify`.

**Comment by jnicklas** [comment]
If you saw my earlier comment: actually, you might be right, didn't really think this through.

**Comment by jnicklas** [comment]
#280 is merged.
