### ISSUE TITLE
Newbie trying to use Pundit on the create functionality

### ISSUE THREAD

**Issue by hyperjuice** [elabs/pundit#285]
Hi, I have a simple CRUD app I'm building: https://github.com/hyperjuice/swuit/tree/punditbug. You can see my work up until this issue I'm having by visiting www.swuit.me.

Scenario: 
1. User #5 is logged in
2. Going to this user's dashboard is at this path: http://localhost:3000/users/5/ (app/views/users/show.html.erb)
3. If I go to http://localhost:3000/users/4/ in the same browser tab, I'm able to see user #4's dashboard, which is fine for right now.
4. When I go to http://localhost:3000/users/4/products (app/views/products/index.html.erb), I see the products for user #4, which is fine (even though I'm logged in as user #5).
5. The problem is that when I go to http://localhost:3000/users/4/products/new, I'm able to submit a new product for user #4, even though I'm logged in as user #5.
6. I've been trying different fixes, with no success.

Could you look at my code and tell me what I'm doing wrong? I'm able to prevent editing by a user that didn't make the product, which is great. I love Pundit!

Other files of interest for this question:
1. products_controller.rb
2. product_policy.rb

I hope this is enough info to go on. Thanks in advance!

/Darrell
darrellcohn@gmail.com

**Comment by deefour** [comment]
You should have a `ProductPolicy` with a `new?` and `create?` method *(there should be others, but I'm just going to cover the ones relevant to your question)*

```ruby
class ProductPolicy < ApplicationPolicy

  def new?
    record.user_id == user.id
  end
  
  def create?
    new?
  end

end
```

Now, in your `ProductsController` you can do something like this in your `new` and `create` methods.

```ruby
class ProductsController < ApplicationController

  before_filter :new_product, only: [ :new, :create ]
  
  def new
    authorize @product
    
    # render the form
  end
  
  def create
    authorize @product
    
    # persist the form data and redirect.
  end
  
  private
  
    def new_product
      @product = Product.new(user_id: params[:user_id])
    end
  
end
```

The `:user_id` in `params[:user_id]` above should be replaced with whatever the token is in your routes for the user in `/users/[token here]/products/new`.

The idea here is, you're instantiating a new `Product` and setting it's ownership to that of the user id in the URL. You're then checking the *currently logged in user* as being that product's owner in the `ProductPolicy`.


I don't know the specifics of your app, but I'd question why when a user is logged in you don't instead simply have a `/products/new` route. IMO, it doesn't really make sense to nest these resources.

**Comment by hyperjuice** [comment]
That did it! Thanks so much. I hear you about the nested resources. As I'm new to Rails, I'm just trying it out, since I recently learned it. But it's great to get feedback from an experienced developer like yourself.

All the best and thanks again!
