### ISSUE TITLE
Demodulizing class name for strong parameters breaks with default input naming

### ISSUE THREAD

**Issue by tristanm** [elabs/pundit#286]
Thanks for this awesome gem; I'm absolutely loving it.

I've come across an interesting situation with strong parameters. With a namespaced model, e.g. `Client::SubscriberList`, Pundit will demodulize the class name and `require` it, i.e. it will enforce:

    params.require(:subscriber_list).params(...)

rather than

    params.require(:client_subscriber_list).params(...)

However, Rails' `form_for` (and therefore [Simple Form][1], [Formtastic][2], et. al.) will generate inputs with the module prefixed in the name, e.g.:

    <input name="client_subscriber_list[some_attribute]" ... />

Which, of course, will lead to `{ "client_subscriber_list": { "some_attribute": "xxxx" } }` being submitted and raising an `ActionController::ParameterMissing` error (because `subscriber_list` is required but missing).

It appears that the demodulization at [lib/pundit.rb#L141][3] goes against Rails' default input naming for namespaced models... or is there something I've missed?

If removing the demodulization is an option, I'm more than happy to do a pull request for this.

[1]: https://github.com/plataformatec/simple_form
[2]: https://github.com/justinfrench/formtastic
[3]: https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L141

**Comment by Envek** [comment]
@tristanm please check whether #297 fixes this issue for you or not. It should.
