### ISSUE TITLE
user always nil

### ISSUE THREAD

**Issue by itay-grudev** [elabs/pundit#287]
For some reason ```user``` in policies is always ```nil```. I am using Sorcery for authentication if that matters. I don't know where to start debugging from. Please advise.

**Comment by itay-grudev** [comment]
Solved it. I apologise for wasting time and space!

**Comment by georgekettle** [comment]
**UPDATE**
Ahhhh never mind guys.... I had to add the form authenticity token to my form.
<%= hidden_field_tag 'authenticity_token', form_authenticity_token %>

I found the solution on this page if you're interested:
https://stackoverflow.com/questions/18423718/rails-devise-current-user-is-nil
