### ISSUE TITLE
Undefined method `skip_authorization` when testing in rspec

### ISSUE THREAD

**Issue by asiniy** [elabs/pundit#288]
I have a usual controller which use `after_action :verify_authorized`, so I need to use `skip_authorization` sometimes.

It's working great in development env, but I meet troubles with testing because of rspec can't find `skip_authorization` method!

``` ruby
  1) ItemsController GET index redirects to the show if params[:id] present
     Failure/Error: get :index, { id: item.id }, valid_session
     NameError:
       undefined local variable or method `skip_authorization' for #<ItemsController:0x0000000940b3f8>
     # ./app/controllers/items_controller.rb:8:in `index'
```

Of course, I've required `require 'pundit/rspec'` in my `rails_helper.rb`.

So, what I should do?

**Comment by beanieboi** [comment]
hey,

to skip authorization you have to skip the before filter. this has nothing to do with Pundit, just tell Rails to skip the action.
in your case it would be

```
skip_after_action :verify_authorized # all actions are unrestrictedly accessible
```

**Comment by quekshuy** [comment]
The README states that...

```
If you're using verify_authorized in your controllers but need to conditionally bypass verification, you can use skip_authorization.
```

Is this still accurate?

**Comment by ce07c3** [comment]
`pundit.rb`:

````ruby
  def skip_authorization
    @_pundit_policy_authorized = true
  end
````

**Comment by jnicklas** [comment]
My guess is that you're using an old version of Pundit. `skip_authorization ` is pretty new.
