### ISSUE TITLE
A policy_scope with additional context

### ISSUE THREAD

**Issue by abitdodgy** [elabs/pundit#289]
I have a Workspace model that has many projects, and many users through memberships. The project model has a `private` flag. Admins can see all projects in a workspace. Members can only see public projects.

```ruby
class Workspace
  has_many :memberships
  has_many :users, through: :memberships
  has_many :projects
end
```

In the ProjectsController index action could look like this, but I'd rather not apply this pattern.

```ruby
class ProjectsController < ApplicationController
  def index
    @projects = if @workspace.admins.include?(current_user)
      @workspace.projects
    else
      @workspace.projects.public    
    end
  end
```

The above code doesn't map nicely to the PolicyScope pattern that pundit provides. The PolicyScope has no concept of the workspace, here.

```ruby
class ProjectsController < ApplicationController
  def index
    @projects = policy_scope(Project.where(workspace: @workspace))
  end
end
```

Here's the issue. The Scope class in ProjectPolicy has no idea about the @workspace. So we can determine the user's level of authorization. Since his Membership is the model that stores its auth level.

```ruby
class ProjectPolicy < ApplicationPolicy
  class Scope
    def resolve
      if workspace.admins.include?(user) # <--- There's no workspace in this context!
        scope.all
      else
        scope.where(private: false)
      end
    end
  end
end
```

Sorry if this has been asked before; I scoured the issues and couldn't find anything I could use. How do the pundits go about this situation?

**Comment by abitdodgy** [comment]
One way I can think of is to use the WorkspacePolicy and return a scope. This means skipping the ProjectPolicy.

```ruby
class ProjectsController < ApplicationController
  def index
    @projects = WorkspacePolicy.new(current_user, @workspace).projects_scope
  end
end
```
Then in the WorkspacePolicy.

```ruby
class WorkspacePolicy < ApplicationPolicy
  alias_method :workspace, :record

  def projects_scope
    if workspace.admins.include?(user)
      workspace.projects.all
    else
      workspace.projects.public
    end
  end
end
```

Any thoughts? A better way?

**Comment by jnicklas** [comment]
Personally I probably would have used a `join` in the `ProjectPolicy`. Something like:

``` ruby
class ProjectPolicy < ApplicationPolicy
  class Scope
    def resolve
      outer_joins(:workspace).merge(Workspace.outer_joins(:admins)).where({ users: { id: user.id }).or(private: false).uniq
    end
  end
end
```

Since Rails *still* doesn't have outer_joins, you can use this: https://github.com/elabs/ar_outer_joins

It's probably wrong somehow, I haven't tested the code at all, but you get the idea. This accurately reflects what you actually have to do to figure out which projects you are allowed to load.

**Comment by abitdodgy** [comment]
@jnicklas thanks for chiming in. This is a good suggestion. I'll try it out. In the end, I opted to change the user context so that the authorization takes place on the Membership record. So instead of passing in the user, I'm passing in the Membership in the Workspace. This avoids the need to lookup the workspace in the ProjectPolicy scope.

```
class UserContext
  def initialize(membership)
    # ...
  end
end

class ProjectPolicy < ApplicationPolicy
  class Scope
    def resolve
      if user.admin?
        scope.all
      else
        scope.where(private: false)
      end
    end
  end
end
```

The membership record became my pundit user. But this is becoming limitted as my business logic grows. I'm thinking this was a bad idea.

Thanks again!
