### ISSUE TITLE
Default exception message can trigger ActionDispatch::Cookies::CookieOverflow

### ISSUE THREAD

**Issue by eliotsykes** [elabs/pundit#293]
`ActionDispatch::Cookies::CookieOverflow` is triggered when Pundit generates an overly long message and its stored in the flash/session, e.g.:

```ruby
  ...
  rescue Pundit::NotAuthorizedError => e
    flash[:alert] = e.message
  end
```

I suspect the following line is responsible:

```ruby
message = options.fetch(:message) { "not allowed to #{query} this #{record.inspect}" }
```
https://github.com/elabs/pundit/blob/145d7592c0028c26e61e8a9569ed3440323eaa40/lib/pundit.rb#L24

If `record.inspect` returns a long enough string this would cause the 4kb cookie storage limit to be exceeded.

**Comment by jnicklas** [comment]
You really should not be storing error messages in the flash. Error messages are meant for consumption by programmers and they may reveal details about your system that you do not want to reveal. You should construct your own error message from the details provided by Pundit (if you need to) or simply show a "Not authorized" generic error message. I think the generic error message is the best option unless you're building an API which others can consume and you want to reveal more about the cause of the error.

**Comment by eliotsykes** [comment]
@jnicklas agreed. 

So forgetting the flash/session problem. Is it worth revisiting including the `record.inspect` output in the message? This message is potentially much longer than a short summary. Exception messages tend to be pretty succinct. The `record` (and `query`) are available on the error object for debugging needs.

**Comment by jnicklas** [comment]
There was a big collective Hallelujah when we changed it to inspect recently. I'm guessing changing it back would piss a lot of people off a lot ;)

**Comment by eliotsykes** [comment]
Oh right, best not cause an uprising! Thanks for explaining, the quick responses, and of course Pundit!
