### ISSUE TITLE
catch not allowed error and return 401

### ISSUE THREAD

**Issue by anklos** [elabs/pundit#294]
Hi there,

First thanks a lot for building this awesome gem!

I am using pundit for many controller authorization, just wonder is there a good way to catch all the Pundit::NotAuthorizedError in the controller and return 401 as response? Otherwise rails will catch the error and returns 500 internal error.

Now I am doing things like this `authorize @post` in the controller.

Thanks!

**Comment by jnicklas** [comment]
Yes. It's documented in the README. https://github.com/elabs/pundit#rescuing-a-denied-authorization-in-rails
