### ISSUE TITLE
ArgumentError when policy not found

### ISSUE THREAD

**Issue by jaredbeck** [elabs/pundit#305]
Given a policy that can't be found, because I forgot to inherit ApplicationPolicy,

```ruby
def DerpPolicy # I forgot to inherit ApplicationPolicy
end
```

and a controller that attempts to find that policy,

```ruby
def DerpsController < ApplicationController
  def create
    derp = Derp.new
    authorize derp
  end
end
```

pundit raises an ArgumentError.

```
ArgumentError:
 wrong number of arguments (2 for 0)
# [snip]/gems/pundit-1.0.1/lib/pundit.rb:62:in `initialize'
# [snip]/gems/pundit-1.0.1/lib/pundit.rb:62:in `new'
# [snip]/gems/pundit-1.0.1/lib/pundit.rb:62:in `policy!'
# [snip]/gems/pundit-1.0.1/lib/pundit.rb:137:in `policy'
# [snip]/gems/pundit-1.0.1/lib/pundit.rb:115:in `authorize'
# ./app/controllers/derps_controller.rb:4:in `create'
```

Instead, it would be nice if pundit raised a more helpful error, like PolicyNotFound.

**Comment by novotarq** [comment]
I took a brief look at it (since I had a similar errors too) and it seems like there are two solutions:

```
    def policy!(user, record)
      PolicyFinder.new(record).policy!.new(user, record)
      rescue ArgumentError
        raise NotDefinedError, "unable to find policy for `#{user.inspect}` and `#{record.inspect}`"
    end
```
or
```
    def policy!(user, record)
      policy = PolicyFinder.new(record).policy!
      arity = policy.instance_method(:initialize).arity
      raise NotDefinedError, "unable to find policy for `#{user.inspect}` and `#{record.inspect}`" if arity != 2 && arity != -1
      policy.new(user, record)
    end
```

Opinions?

**Comment by jnicklas** [comment]
But the policy what found! You just passed in the wrong kind of arguments to it, which resulted in an ArgumentError. Everything seems good to me.

**Comment by jaredbeck** [comment]
> But the policy what found! You just passed in the wrong kind of arguments to it, which resulted in an ArgumentError. Everything seems good to me.

Oh, is it actually finding the `DerpPolicy`?  OK, that's fine then.  Thanks.
