### ISSUE TITLE
Accept parameter in policy method

### ISSUE THREAD

**Issue by zoot123** [elabs/pundit#306]
I have a similar problem like that https://github.com/elabs/pundit/issues/239 . I would like to check if the current_user is like a passed user. I know there is a way to do this with additional context but I think that is much work for this "easy" check.
Is there any simple way to pass parameters?
something like this

Controller:

```
def destroy_abo
  authorize @broadcast, @current_user, @user
  ...
end
```

Policy

```
def destroy_abo?
  return true if (current_user.id == user.id)
end
```

**Comment by ce07c3** [comment]
Where did you get `user` from? If it's associated with `@broadcast`, then you don't need to pass it along.

**Comment by zoot123** [comment]
The @broadcast has a has_Many reference to User and the @user is the user which should destroyed from the reference @broadcast.users
Users should only destroy her own record.

**Comment by ce07c3** [comment]
Ok, so:

* Authorize the broadcast: make sure the current user is in it
* Delete the user from the broadcast

The second step does not need to be authorized anymore, it just needs to be correct. I.e. remove the current user from list of users associated with the broadcast.
