### ISSUE TITLE
How to authorize an instance of user if user is given permission

### ISSUE THREAD

**Issue by SupremeA** [elabs/pundit#307]
I have a user model(worker) that owns a report. The worker can grant temporary access to viewing a report to a manager(user) (another user type). 

I am trying to use Pundit to make sure that only the correct manager can access the report of the correct worker(user). 

I have a report_policy.rb in my pundit policies folder and I want that policy to check a related model called reportapproval(a model that temporarily grants access to managers) to see if the current_manager has access to the report they are asking for. 

How can I set an access right in pundit policy for report that checks the reportapproval(model) issued for that particular manager. I have this right now in my policy folder...

   report_policy.rb

    class ReportPolicy < ApplicationPolicy
     attr_reader :user, :report

     def initialize(user, report)
        @user = user
        @report = report
      end

     def show?
       if @user.reportapprovals do |ra| ra.manager == @user #each reportapproval has a manager attached to it
       end
     end

My controller for reports is as follows...

    class Managers::ReportsController < ApplicationController
      before_action :set_report, only: [:show, :edit, :update, :destroy]
      before_filter :authenticate_manager!
    
      def show
        @report = Report.find(params[:id])
        authorize @report
      end

Not sure of how to do this correctly or if I am even on the right path?

ADDITIONAL INFORMATION:
I have also tried redirecting the report model to the reportapprovals_policy in an effort to check the reportapproval model but I keep getting the following error:

    Unable to autoload constant ReportapprovalPolicy, expected /home/vagrant/code/TestApp/app/policies/reportapproval_policy.rb to define it

**Comment by novotarq** [comment]
pundit_user is a helper method for controllers

**Comment by SupremeA** [comment]
Ok just saw that error. I removed it from the model. Thanks

**Comment by deefour** [comment]
Shouldn't the `Report` know about the `ReportApprovals` too?

```ruby
def show?
  @report.approvals.where(user_id: @user.id).exists?
end
```

**Comment by SupremeA** [comment]
Ok thank you deefour for your input that fixed the problem halfway. The issue I am having is that since there are two user types manager and tenant, I cant get the show method to work for both I have to use your statement like this 

    def show?
      @report.approvals.where(manager_id: @user.id).exists?
    end

when I try 

    def show?
      @report.approvals.where(user_id: @user.id).exists?
    end

Its not working for neither manager or tenant.

**Comment by deefour** [comment]
How about a literal query then?

```ruby
def show?
  @report.approvals.where("user_id = ? or manager_id = ?", @user.id, @user.id).exists?
end
```

**Comment by SupremeA** [comment]
It says Im passing 3 arguments for 1 so nope. What about the manually specifying policy class does this method go in the controller or model

    class Post
      def self.policy_class
        PostablePolicy
      end
   end

**Comment by SupremeA** [comment]
GOT IT! I created a uniques policy in within the policy file like this:

      def other_user?
        @user.report(tenant_id: @user.id)
      end

Then in the tenant controller I called the action like so...

    def show
        @report = Report.where(params[:id])
        authorize @report, :other_user?
    end

Thanks for your help! Happy to be done with this! YEAH!!!!!!

**Comment by cireficc** [comment]
@SupremeA I would suggest asking questions like this on [StackOverflow](http://stackoverflow.com/) next time. It's not very polite to clog the Issues tracker...

**Comment by SupremeA** [comment]
I understand and apologize. I actually did ask the question on SO but received No responses. So my last resort was to go here. But again, I apologize and thank everyone for the help.
