### ISSUE TITLE
Composing scopes idea

### ISSUE THREAD

**Issue by nruth** [elabs/pundit#310]
I'm looking at this code in pundit/policy_finder.rb and wondering if it could be changed to allow dynamic scope definitions, to support composition / multiple-inheritance, as explained in [stackoverflow](http://stackoverflow.com/questions/32166733/pundit-authorisation-multiple-inheritence-scopes-modules)

```ruby
def scope
  policy::Scope if policy
rescue NameError
    nil
end
```

```
def scope
  if policy
    policy::Scope || (policy.scope if policy.respond_to?(:scope))
  end
rescue NameError
    nil
end
```

Does this look like a viable PR (with tests etc) or is there a reason for using class definitions I haven't thought of?

**Comment by jnicklas** [comment]
Be aware that `policy` in this case is the policy **class** not an instance thereof. I can't think of anything that such a class method could do that would be in any way sensible. The only thing I can think of is doing really evil stuff with thread-locals, which is not something we should encourage.

**Comment by jnicklas** [comment]
Can you provide a user case where you would want to use this?

**Comment by nruth** [comment]
Hej Jonas
Thanks for looking at this!

While writing up a reply I spotted a simpler solution that doesn't need what I was talking about, so I'm closing the issue.

Method definitions and modules within the scope class work just fine. I got myself stuck on another idea somehow and missed the simple solution.

I wanted to build a whitelist for resource access, and am now doing it like this:

```ruby
class ApplicationPolicy < BlankPolicy
  attr_reader :admin, :record

  def initialize(admin, record)
    raise Pundit::NotAuthorizedError, "must be logged in" unless admin
    @admin = admin
    @record = record
  end

  # this should be extended and added to by specific policy scopes as they add access
  def whitelisted_ids
    []
  end

  def resolve
    if admin.product_owner?
      scope.all
    else
      scope.where(id: whitelisted_ids)
    end
  end
end
```

with policy classes like this:

```ruby
class PagePolicy < ApplicationPolicy
  # enable assigned work to be done
  include WorkAssignmentsSharedPolicy
  # enable section editors to update their tagged content
  include TagsAclSharedPolicy

  class Scope < ApplicationPolicy::Scope
    include TagsAclSharedPolicy::ScopeExtension
    include WorkAssignmentsSharedPolicy::ScopeExtension
  end
end
```

```ruby
module TagsAclSharedPolicy
  module ScopeExtension
    def whitelisted_ids
      super + scope.tagged_with(admin.tags_acl, any: true).pluck(:id)
    end
  end
  # then show? edit? etc definitions
end
```

And this class doesn't have tags or work assignments, but inherits permission from the question it belongs to
```ruby
class AnswerPolicy < ApplicationPolicy
  class Scope < Scope
    def whitelisted_ids
      # add answers in questions permitted by question policy
      super + QuestionPolicy::Scope.new(admin, Question.all)
                                   .resolve.map(&:answer_ids)
                                   .flatten
    end
  end
end
```

I may turn the longer writeup into a blog post or something, but it's probably not very interesting, and the crux of it is shown in the code above.
