### ISSUE TITLE
Add ability to permit all attributes and/or blacklist attributes in Policy

### ISSUE THREAD

**Issue by cireficc** [elabs/pundit#312]
Currently one can *whitelist* attributes in a Pundit Policy like this:

```ruby
 # app/policies/post_policy.rb
 class PostPolicy < ApplicationPolicy
     def permitted_attributes
         if user.admin? || user.owner_of?(post)
             [:title, :body, :tag_list]
         else
             [:tag_list]
         end
    end
end
```

However, what if we want to *blacklist* attributes (permit all *except* certain attributes)? We can do this in our Rails controller like this:

```ruby
def post_attributes
    params.require(:post).permit!.except(:title, :body)
end
```

if for example the `Post`s `title` and `body` shouldn't be updated after submission. What if we want to allow only an admin to update `title` and `body`, and other users could update any of the other 20+ attributes on a `Post`? Well, Pundit works for the authorization, but *we can't blacklist attributes through Pundit* (in a way that makes sense)!

According to [the source](https://github.com/elabs/pundit/blob/master/lib/pundit.rb), there's only a [`permitted_attributes`](https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L142) method:

```ruby
def permitted_attributes(record)
    name = record.class.to_s.demodulize.underscore
    params.require(name).permit(*policy(record).permitted_attributes)
  end
```

but nothing allowing us to blacklist attributes, because the thing is hard-coded to only [`permit`](https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L144) attributes.

In our controller, we would normally use Pundit like this:

```ruby
def post_params
    params.require(:post).permit(policy(@post).permitted_attributes)
end
```

But we would also like to be able to do this:

```ruby
def post_params
    params.require(:post).permit!.except(policy(@post).blacklisted_attributes)
end
```

in order to move to a blacklisting approach.

**Comment by jnicklas** [comment]
Blacklisting is usually a bad idea in any context, I don't think we should make it easier.

**Comment by cireficc** [comment]
@jnicklas Sometimes blacklisting is fine, for example with a public API where 99% of the data won't pose a security issue and is/*should* be completely public. Crowd-sourced data, for instance, where only attributes like `data_author` should be blocked from being updated.

And remember, we can scope these blacklists based on role, or whatever else on our User model, so I really don't see how it's an issue.

Some [comments from StackOverflow](http://stackoverflow.com/questions/15528649/how-to-permit-all-attributes-besides-user-id-using-strong-parameters#comment37733851_15528745), [just because](http://stackoverflow.com/a/18039034/1986871).

All the Rails guides out there say that whitelisting is the approach that should be used, but there are valid circumstances where blacklisting is okay too. Since Pundit gives us even greater control over the whitelists, why wouldn't it allow us to give even *more security* concerning the (obviously dangerous is a lot of cases) blacklists?

I see no downside, honestly. People who are currently using blacklists would only gain benefit from using Pundit to scope them.

And personally, whitelisting the several 30+ parameter models that I have repeatedly for each role that only have **very slight differences in updateable attributes** is really the opposite of what I (or probably anybody) wants to be doing.

**Comment by jnicklas** [comment]
Pundit is in no way preventing you from blacklisting stuff, it only makes it *more convenient* to whitelist stuff. I see no reason to change that. Whitelisting *is* the best practice. Even Rails has made the API for blacklisting less convenient. You can still use Pundit and use it to blacklist, but we're not going to build that into the gem.
