### ISSUE TITLE
Confusion on using Pundit with Engines // Admin Routes

### ISSUE THREAD

**Issue by thewatts** [elabs/pundit#320]
I'm having a little trouble fully understanding how to use Pundit.

There are 2 things I'm confused on:

---

##### 1. Policies that are scoped within a namespace.

I have scoped controllers (that are within engines), ex:

```ruby
module Thing
  class Admin::UsersController < Admin::ApplicationController
    # etc
  end
end
```

But when I tell pundit to `authorize User`, it says it's looking for the `Thing::UserPolicy` (instead of the `Thing::Admin::UserPolicy`.

---

##### 2. Auto-rejecting non-admins from all Admin controllers

My default thoughts for locking out non-admin users would be to place a policy within the `Admin::ApplicationController`, that auto checks to see if a user is an admin, and if not - they get rejected. I'm not quite sure how this would look in Pundit though.

Would this just be a [headless policy](https://github.com/elabs/pundit#headless-policies), such as `AdminPolicy` that would auto reject all actions if the user is not an admin?

---

Thanks!

**Comment by guzart** [comment]
**RE: 1. Policies that are scoped within a namespace.**

I would also like to know what is the proper way to handle authorization for namespaced controllers.

**RE: 2. Auto-rejecting non-admins from all Admin controllers**

I use a headless policy and method missing to authorize everything, but you could get more granular.

```
# app/controllers/admin/application_controller.rb
before_action :authorize_admin_user!
 
def authorize_admin_user!
  authorize :admin, "#{params[:action]}?".to_sym
end
```

```
# app/policies/admin_policy.rb
AdminPolicy = Struct.new(:user, :admin) do
  def method_missing(_name, *_args, &_block)
    user.admin?
  end
end
```

**Comment by guzart** [comment]
This looks like a sensible solution for No. 1

https://github.com/elabs/pundit/issues/308

**Comment by ramaboo** [comment]
At Doorman.co we had this problem and have submitted https://github.com/elabs/pundit/pull/331 which allows you to to pass an array to authorize like this:

```
authorize [:thing, :admin, User]
```

Which should load: `Thing::Admin::UserPolicy`

**Comment by jnicklas** [comment]
#331 is now merged, which provides a pretty sensible solution to this problem.
