### ISSUE TITLE
Used ApplicationPolicy if no <MODEL>Policy is present as shared policy, so I do not have to define a Policy file for all my models

### ISSUE THREAD

**Issue by fddayan** [elabs/pundit#321]
The idea is that: 
if you have not define a <MODEL>Policy, it will load `AppliactionPolicy`, that will have the shared policy. This is to avoid `Policy not found` Exception. 

I'm introducing `Pundit` to a new project with a lot of models and I have to created them all manually. Also most of them share the same policy.

**Comment by ce07c3** [comment]
@fddayan Just create a base policy and let all the others inherit from it. Having an implicit default policy is paramount to insecurity and insane defaults. ;)

**Comment by jnicklas** [comment]
Agreed. It also makes debugging much harder.
