### ISSUE TITLE
pundit_user with additional context not called in ActiveAdmin

### ISSUE THREAD

**Issue by JMCQ87** [elabs/pundit#327]
I'm trying to use the session as additional context for the User, as [described here](http://stackoverflow.com/questions/20362459/accessing-session-parameters-in-pundit-policy), but within ActiveAdmin, using the Pundit Adapter.

The pundit_user method in the application_controller is never called, and therefore, when a policy tries to access the context, it is nil. Might this be an issue with the Pundit Adapter?

The project uses Pundit 0.3.0 and activeadmin 1.0.0.pre.

**Comment by jnicklas** [comment]
Yeah, you need a newer version of Pundit.

**Comment by dukedave** [comment]
Late to the party, but, was this the solution?
```ruby
  class PunditAdapter
    def user
      UserContext.new super
    end
  end
end
```

**Comment by AvaelKross** [comment]
@dukedave it looks promising, but I can't access the request there (while I can do it in ApplicationController), and additional context usually depends on some request-scoped vars

**Comment by sonololo** [comment]
The problem still persists, can't access pundit_user in ApplicationController in Pundit 2.1.0, and I do need extra parameters to pass to policy context
