### ISSUE TITLE
`for_actions` feature

### ISSUE THREAD

**Issue by quolpr** [elabs/pundit#338]
In my project I realized feature, that helps me to avoid code duplication.
For example:
```ruby
for_actions :index, :create, :update, :destroy do
  user.has_role? :super_admin
end
```
It will generate methods `index?`, `create?`, `update?`, `destroy?` with the same logic.
What do you think? I can make pull request.

**Comment by quolpr** [comment]
Oh, I just noticed that all policies are simple ruby objects. Can we make base policy - `BasePolicy`, like in  rails `ActionController::Base` or it is contrary philosophy of the pundit?

**Comment by damien** [comment]
@quolpr I like the intent of this feature, but in the spirit of keeping Pundit focused on simple ruby objects, would be preferable to make this a module mixin? Example:

```ruby
module SuperAdminPolicyMixin
  def is_super_admin?
    user.has_role? :super_admin
  end
  alias_method :index, :is_super_admin?
  alias_method :create, :is_super_admin?
  alias_method :edit, :is_super_admin?
  alias_method :update, :is_super_admin?
end
```

```ruby
class FooPolicy
  include SuperAdminPolicyMixin
  # ...
end
```

I believe this would be equivalent to your above example. Alternatively, you could just define your own `is_super_admin?` method and alias it directly in your policy.

**Comment by quolpr** [comment]
@damien good solution, but mixin(or alias) is hard to read.

**Comment by bolshakov** [comment]
@quolpr 

You can define your own DSL. For example

```ruby
module PunditDSL
  def allows(role, to: )
    Array(to).each do |action_name|
      define_method "#{action_name}?", do 
         user.has_role?(role)
      end
    end    
  end
end

class FooPolicy
  extend PunditDSL
  
  allows :super_admin, to: [:create, :destroy, :update]
  allows :admin, to: :index
end
```

**Comment by quolpr** [comment]
@bolshakov it is better that I offered. Thank you :)

**Comment by jnicklas** [comment]
One of Pundit's explicit design goals is not to have a common base class that everything inherits from. I prefer leaving this up to the user to decide. As mentioned in the README:

> Remember that all of the policy and scope classes are just plain Ruby classes, which means you can use the same mechanisms you always use to DRY things up. Encapsulate a set of permissions into a module and include them in multiple policies. Use alias_method to make some permissions behave the same as others. Inherit from a base set of permissions. Use metaprogramming if you really have to.
