### ISSUE TITLE
undefined method `policy' while testing with RSpec views specs

### ISSUE THREAD

**Issue by TheNeikos** [elabs/pundit#339]
I have included Pundit in my ApplicationController, however, by adding a `byebug` just below `include Pundit` I am certain that it does never get actually loaded when testing views in RSpec.

Which means that right now, including the pundit rspec helper is not useful and has to be worked around using instance variables that are then injected, hardly ideal and hopefully just temporary.

I have also included `pundit/rspec` in my `spec/spec_helper.rb` at the top. My gemfile:

```
source 'https://rubygems.org'

gem 'rails', github: "rails/rails"
gem 'sprockets-rails', github: "rails/sprockets-rails"
gem 'sprockets', github: "rails/sprockets"
gem 'sass-rails', github: "rails/sass-rails"
gem 'arel', github: "rails/arel"
gem 'rack', github: "rack/rack"

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', github: "rails/coffee-rails"

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Let's use the jquery turbolinks
gem 'jquery-turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Use PaperTrail for versioning
gem 'paper_trail', '~> 4.0.0'
# Use Pundit for authorization
gem 'pundit'
# Use Haml for templates
gem 'haml-rails', '~> 0.9'
# Use simple_form
gem 'simple_form'
# Use Foundation
gem 'foundation-rails'

# Use puma as the app server
gem 'puma', group: [:development, :production]

# Use Capistrano for deployment
gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # We use RSpec for tests :D
  gem 'rspec-rails', '~> 3.0'
  # Use Factory Girl
  gem 'factory_girl_rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', github: 'rails/web-console'
  # We want prettier errors!
  gem 'better_errors'
  # Local mail delivery!
  gem 'letter_opener'
end
```

[The code](https://github.com/TheNeikos/the.wyvern.rocks/blob/a00e7d02edcf223b154a2a0d4dc8a42fc9c20f44/app/views/topics/show.html.haml)
[The test output](https://travis-ci.org/TheNeikos/the.wyvern.rocks/builds/95119512)

**Comment by TheNeikos** [comment]
Is there a way to get someone who might know what the issue is to look at this? This is pretty much stopping me from correctly writing tests for my views. (Since I can still debug them using the Browser, as that works just fine.)

**Comment by TheNeikos** [comment]
In a moment of 'I cannot break it further than not working' I tried including Pundit in the ApplicationHelper, and it worked, so I guess that is one way that is more elegant. 

Still don't think that is the correct way though.

**Comment by deepredsky** [comment]
I would just stub the view 

For example

```ruby
  before do
    allow(view).to receive(:policy).and_return(double("some policy", new?: true))
  end
```

Here is the relevant doc, that might help you.

https://www.relishapp.com/rspec/rspec-rails/v/3-0/docs/view-specs/view-spec#passing-view-spec-that-stubs-a-helper-method

**Comment by jnicklas** [comment]
It seems like view specs do not inherit helper methods from the controller (which makes sense if you think about it), so this is really somewhat expected and @deepredsky's workaround is the right one.

**Comment by koenpunt** [comment]
In addition to @deepredsky's solution, you could instantiate the policy:

```rb
allow(view).to receive(:policy) do |record|
  policy = Pundit::PolicyFinder.new(record).policy
  policy.new(restaurant.owner, record) if policy
end
```

**Comment by sLe1tner** [comment]
Can someone help me figure out how to apply the solutions presented by @deepredsky and @koenpunt in specs for a view helper method that uses `policy`?
So far all of my attempts ended in _X_ `does not implement: policy`, where _X_ is whatever I'm trying to stub for, like `view` for example.

**Comment by tomdunning** [comment]
Combining the content above from @sLe1tner and @koenpunt , here is a full solution for the future sufferers which come across this page.

spec/rails_helper.rb
`config.include PunditSpecHelper, type: :view`

spec/support/pundit_spec_helper.rb
```
module PunditSpecHelper

  def enable_pundit(view, user)
    without_partial_double_verification do
      allow(view).to receive(:policy) do |record|
        Pundit.policy(user, record)
      end
    end
  end

end
```

Example usage in a view:

```
require 'rails_helper'

RSpec.describe 'countries/index', type: :view do
  before(:each) do
    assign(:countries, [create(:uk), create(:germany)])
  end

  let(:user) { create(:admin) }

  it 'renders a list of countries' do
    enable_pundit(view, user)

    render

    expect(rendered).to match('my content')
    # more expectations here...
  end
end
```
