### ISSUE TITLE
Different permitted parameters per action?

### ISSUE THREAD

**Issue by RST-J** [elabs/pundit#340]
Hello,
I'm working with pundit for the first time and like the [`permitted_attributes helper`](https://github.com/elabs/pundit#strong-parameters) as it bundles together (write) access control for actions and attributes.
However, I now encounter the situation where I want to allow different sets of parameters for different actions.
Would you consider adding such a feature if I prepared a pull request?

My idea is to extend permitted_attributes this way:
```ruby
def permitted_attributes(record)
  name = record.class.to_s.demodulize.underscore
  action_params_method = "#{params[:action]}_attributes"
  attributes_method = policy(record).respond_to?(action_params_method) ?
    action_params_method : :permitted_attributes
  params.require(name).permit(*policy(record).send(attributes_method))
end
```

**Comment by Silex** [comment]
#299 should be considered if you refactor this.

**Comment by jnicklas** [comment]
I'm reading this as that the method would have the name `create_permitted_attributes` for example? That seems a bit misleading to me. How about something more like `permitted_attributes_for_create`, I think that makes it clearer. Principally I think this is a neat addition :+1:
