### ISSUE TITLE
pundit-matchers feedback

### ISSUE THREAD

**Issue by chrisalley** [elabs/pundit#342]
I recently published a set of RSpec matchers for Pundit:

https://github.com/chrisalley/pundit-matchers
https://rubygems.org/gems/pundit-matchers

Before bumping the version number to 1.0.0, some feedback on the API and documentation would be great. 

I still need to write an independent test suite. Currently the app that the matchers are used in acts as a confirmation that the matchers work as expected. Good strategies for testing RSpec matchers would helpful too.

**Comment by jnicklas** [comment]
If it's useful to you then go ahead and mark it as 1.0.0. I quite like the look of the specs, maybe even better than the action focused style that we bundle with pundit.

**Comment by chrisalley** [comment]
Thanks for your kind words @jnicklas. I've just released version 1.0.0.

A mention in the "External Resources" section of the Pundit readme would be great, if you're willing.

**Comment by jnicklas** [comment]
Sure, send a PR!
