### ISSUE TITLE
Implementing different policies for the same class

### ISSUE THREAD

**Issue by bolshakov** [elabs/pundit#344]
I have an REST API application with administration interface built using [ActiveAdmin](http://activeadmin.info). It uses [Pundit adapter](http://activeadmin.info/docs/13-authorization-adapter.html#using-the-pundit-adapter) to restrict access for different types of `AdminUser`s (I have admin, crm manager, and cms manager roles).

Thus, I use Pundit to authorize `AdminUser`s to access our domain model objects.

Now, I have to implement authorization of `ApiClient`s for the same objects via REST API interface.

Thereby, I need different policies for the same class for two different authorization contexts (`AdminUser` and `ApiClient`)

My current decision is to use custom `PolicyFinder` and ignore `Pundit.policy` method.

```ruby
class AdminPunditAdapter < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    policy_finder = AdminPolicyFinder.new(subject)
    policy = policy_finder.policy!.new(user, subject)
    
    policy.respond_to?(action) && policy.public_send(action)
  end
end

class AdminPolicyFinder < Pundit::PolicyFinder 
  def find
    policy = super  
    "Admin#{policy}" if policy
  end
end
```

This solution doesn't look perfect, I'd rather expect either from `PolicyFinder` to be able to return different policies depending on authorization context or from `Pundit.policy` method to be configurable with policy finder class.

**Comment by jnicklas** [comment]
There are a *ton* of discussions about this particular issue. Please search around a bit and read them before commenting further on this issue.
