### ISSUE TITLE
Scopes for nested resources

### ISSUE THREAD

**Issue by george1minus1** [elabs/pundit#345]
Firstly I'll say that this question may be a result of me misunderstanding how to do this.

On my project I am using nested resources, so I have a Community, that has NewsItems. In the NewsItemsController I want to use a scope to get all the NewsItems but based on the current Community.

Any thoughts on the best way to do this?

**Comment by damien** [comment]
Depends on the context. Pundit classes are plain old ruby objects, so you can reorganize the logic however you like. If I were doing this, I'd assume your NewController has an `:id` parameter that references an individual news item and that news items have a `belongs_to` relation to a Community.

**news_item_policy.rb**
```ruby
class NewsItemPolicy
  # ...

  class Scope
    def initialize(user, scope)
      @user = user
      @scope = scope # For this to work you'll need to provide an instance of NewsItem when you call the policy_scope helper
    end

    # This is the magic method that determines what calling `policy_scope` in a view/controller
    # will return
    def resolve
      # Generic scope for a NewsItem with no context
      # You can query @scope for other information to determine what kind
      # of data you return
      return @scope.all if @scope == NewsItem

      # New scope derived from context provided by an instance of NewsItem
      news_item = @scope
      NewsItem.where(community_id: news_item.community_id)
    end
  end
end
```

**news_item_controller.rb**
```ruby
class NewsItemController < ActionController::Base
  # ..

  def show
    @news_item = NewsItem.find(params[:id])
    @news_items = policy_scope(@news_item) # => All news items within the same community
  end

  # ...
end
```

My assumptions may not be 100% correct and you'll want to change the structure to suite your codebase, but in general that's the sort of structure you'll need to implement to provide more sophisticated logic for Pundit to execute.

**Comment by jnicklas** [comment]
Personally, I'd rather do it the other way around. I'd have my policies ensure that somone can only edit the NewsItems they are supposed to edit, and then in my controllers I'd simply do this:

``` ruby
class NewsItemController < ActionController::Base
  def show
    @community = Community.find(params[:community_id])
    @news_item = @community.news_items.find(params[:id])
    authorize(@news_item)
  end
end
```

Now suppose that a given user can only edit news items of communities they are a member of, you will want to encode this in the policy:

```
class NewsItemPolicy < ApplicationPolicy
  def show?
     record.community.member?(user)
  end
end
```

If I were you I'd also consider *not* nesting the NewsItemController at all, but rather have it at a top level route. Whether that is better or not is a judgement call, and it depends a lot on the situation.

**Comment by leonelgalan** [comment]
If nesting is a must, and I have a similar setup, I found this other approach to be closer to the spirit of Pundit. Pundit's scope is about limiting the results to the user, independent of the community. It should be the controller, aware of `params[:community_id]` to perform that last filter related to that particular request.

Assuming: Communities have many members, where members are simply users.

```ruby
class NewsItemPolicy::Scope < Scope
  def resolve
    if user.admin?
      scope.all
    else
      scope.joins(communities: :members).where users: { id: user }
    end
  end
end
```

```ruby
# Somewhere in your controller
policy_scope(NewsItem).where(community_id: params[:community_id])
```

So far this is working well, I think it provides a better separation of concerns from authorization and controllers.

**Comment by MincePie** [comment]
Has anyone managed to get any of these solutions working? I'm struggling with a similar issue - outlined here: http://stackoverflow.com/questions/39186881/rails-4-pundit-scoped-policy-for-index. Tearing my hair out trying to learn how to use this system.
