### ISSUE TITLE
Incompatibility with rails 3.2 and strong parameters gem

### ISSUE THREAD

**Issue by sobrinho** [elabs/pundit#353]
The strong parameters gem do not allow an array for attributes like this (on older versions, rails 4 does accept):

``` ruby
params.require(:user).permit([:login, :email])
```

Instead you have to pass the attributes splatted like this:

``` ruby
params.require(:user).permit(:login, :email)
```

Because of that the `permitted_attributes(record)` helper do not works.

Would you accept a pull request fixing that? The fix is easy:

```  ruby
params.require(param_key).permit(policy.public_send(method_name))
```

To this:

```  ruby
params.require(param_key).permit(*policy.public_send(method_name))
```

**Comment by jnicklas** [comment]
Huh, I was sure that we'd already fixed this, seems like it got lost in merges somehow.
