### ISSUE TITLE
Pundit::AuthorizationNotPerformedError on ActiveAdmin

### ISSUE THREAD

**Issue by lucianosousa** [elabs/pundit#361]
So, here is my scenario:

I've a ActiveAdmin class, any change[1] I do on this file and try reload the page I receive this error and need reset my app:
`Pundit::AuthorizationNotPerformedError`

What's going on here? Should I do something to avoid this error or it's the regular behavior?

[1] Just add a block like this:
```
  action_item only: :index do
    link_to 'Example', admin_example_path
  end
```

**Comment by neilsmind** [comment]
Pundit::AuthorizationNotPerformedError means that you do not have a policy being called and your rails app is configured to ensure one is being called for each controller action. 

Here is the doc section for an "ordinary rails" app that would apply: https://github.com/elabs/pundit#ensuring-policies-and-scopes-are-used

Also, here's the suggested ApplicationPolicy from ActiveAdmin for use with Pundit:
https://github.com/activeadmin/activeadmin/blob/master/spec/support/templates/policies/application_policy.rb

That's the most likely resolution to your issue...

**Comment by lucianosousa** [comment]
I already have this application policy in my project.

The strange part of this `Pundit::AuthorizationNotPerformedError` error is:

- start rails app, access a page(eg: /admin/users), authorization works fine;
- change the controller, eg: create a new action; add a policy for this new action; access an old action((eg: /admin/users); app raises: `Pundit::AuthorizationNotPerformedError`

**Comment by jnicklas** [comment]
There is nothing in Pundit that would do this. ActiveAdmin is crazy magic, I can't imagine the multitude of ways it could break things.
