### ISSUE TITLE
Expose test helper to clear pundit cache

### ISSUE THREAD

**Issue by f3ndot** [elabs/pundit#362]
In a test of our API I'm trying to perform a POST that's authorized (rocketpants, doorkeeper, devise) as a proper use for the pundit ACL then subsequently a GET request that's unauthorized. Unfortunately, since both the GET and POST calls occur within the same `test` block, the pundit policy cache gets in the way breaking the test.

Currently I don't know of any workaround, so knowing one in the meantime would be great.

```ruby
test 'Shared secret is used for lookup' do
  @controller.stubs(:doorkeeper_token)
             .returns valid_token_for 12

  post :create
  assert_response :success
  first_response = json_parsed_response

  @controller.stubs(:doorkeeper_token)
             .returns nil

  # doing @controller.policies() here returns the cache of the previous
  # RESTful action. Want to be able to clear it.

  # Pundit has cached the policy and current_user is not `nil` as expected but
  # in fact the user with ID 12 as done above.
  get :index, pin: first_response['pin']
  assert_response :success
  second_response = json_parsed_response
  assert first_response['pin'] == second_response['pin']
end
```

**Comment by damien** [comment]
I don't disagree that it'd be nice to have more knobs for any library during testing, but is there a particular need here to test both a get and a post within the same individual test? I find trying to keep a 1-to-1 assertion-to-test ratio avoids a lot of odd issues like this and generally results in less brittle tests.

**Comment by jnicklas** [comment]
I agree with @damien, if you're stubbing out things you're not testing at a high enough level for it to make sense to tests several things in succession. Just isolate each tests and you won't need this.
