### ISSUE TITLE
Starting out with Pundit, more an advice question than issue.

### ISSUE THREAD

**Issue by hail2skins** [elabs/pundit#369]
So, I have a Knowledge Base I'm building for myself and some friends.   I am using Pundit for the first time.   I see you guys recommend tying authorization to the user and the model itself, but I think what I've done to achieve my aim is something you guys would recommend so just checking.

I have a user who signs up.   He then creates a business which automatically creates an admin group for the business.   My initial pundit scope for business articles is I want to limit who can see the index or the articles themselves only to people expressly part of the business admin group (and eventually more).

In my articles_controller I have the following:

```ruby
  def index
    @articles = @business.articles.all
    authorize @business
  end
```

So, I am authorizing the business.   So then in my business_policy.rb I have the following:

```ruby
  def index?
    record.groups.find_by(name: "#{record.name} Admin").memberships.exists?(user_id: user)
  end
```

This appears to achieve my end, at least for index, if somewhat sloppily.   My question is basically if this is how you would anticipate locking down the articles themselves so only people with rights to the business can see them.   Or if I am messing this up entirely?   Thanks for any guidance.

Art.

**Comment by jnicklas** [comment]
This seems fine to me conceptually, and as far as usage of Pundit is concerned. I do think that the way you linked the admin group to the business is rather strange. I would personally never rely on the name of the group for something like that.

**Comment by hail2skins** [comment]
I'll be changing that at some point.   Though, the user has no access to the group, so it's as stable as a true or false in a role table in that the business creates the group.   However, later, users could create different ones so I'll role table it up at some point.   Just learning Pundit and liking it so far :).

Thank you for taking the time to reply and the work on this gem.
