### ISSUE TITLE
Allow to pass context to permitted_attributes method

### ISSUE THREAD

**Issue by n-rodriguez** [elabs/pundit#372]
Hi there!

It would be nice if a context could be passed to ```permitted_attributes``` method.
I totally agree with https://github.com/elabs/pundit#additional-context but I don't think this can be applied to ```permitted_attributes``` method.

I've got this example : 

```
class Customer < ApplicationRecord
  has_many :sale_agreements
end

class House < ApplicationRecord
  has_many :sale_agreements
end

class SaleAgreement < ApplicationRecord
  belongs_to :house
  belongs_to :customer
  belongs_to :user
end

class Customer::SaleAgreementsController < ApplicationController
  def sale_agreement_params
    [:house_id, :user_id, :commission, :state, :should_sign_at, :signed_at]
  end
end

class House::SaleAgreementsController < ApplicationController
  def sale_agreement_params
    [:customer_id, :user_id, :commission, :state, :should_sign_at, :signed_at]
  end
end
```

The same policy is called by the 2 controllers (SaleAgreementPolicy) but I want to be able to return the right params for the right context.

This could be done easily if a hash containing the controller and the action was passed to ```permitted_attributes``` method.

**Comment by guzart** [comment]
You can use different policies for each controller by using namespaced policies. That is, you would have `class Customer::SalesAgreementPolicy` and a `class House::SalesAgreementPolicy`. Inside the controllers you would call authorize with an array, i.e. `authorize([:customer, :sales_agreement])` and `authorize([:house, :sales_agreement])` respectively.

**Comment by jnicklas** [comment]
What @guzart said :+1:

**Comment by n-rodriguez** [comment]
> You can use different policies for each controller by using namespaced policies. That is, you would have class Customer::SalesAgreementPolicy (/policies/customer/sales_agreement_policy.rb) and a class House::SalesAgreementPolicy. Inside the controllers you would call authorize with an array, i.e. authorize([:customer, :sales_agreement]) and authorize([:house, :sales_agreement]) respectively.

Great! Thx!
