### ISSUE TITLE
Authorizing associations?

### ISSUE THREAD

**Issue by CheeseWarlock** [elabs/pundit#374]
What is the recommended way of handling the following case:

    def create
      authorize Box
      params[:toy_ids].each { |toy| authorize Toy.find(toy) }
      Box.create(params)
    end

The above works, but it seems like probably there is something I'm missing in terms of the common pattern of associating things together only if you have permission to those things?

**Comment by deefour** [comment]
Your `BoxController::create` method should typically authorize the user's ability to create a `Box` and nothing more.  Consider letting that action create the `Box` regardless of the `:toy_ids`, but filter those ids to those the user is allowed to put in the box.

I would look at removing the toy authorization you're performing in the controller action and instead create a [`permitted_attributes`](https://github.com/elabs/pundit#strong-parameters) method on the `BoxPolicy`.

I'm happy to help bump you in the right direction even further, but a good deal of this depends on what your `ToyPolicy::create` method looks like.

**Comment by jnicklas** [comment]
Agree with @deefour
