### ISSUE TITLE
how to use authorize function in ApplicationController?

### ISSUE THREAD

**Issue by megetron** [elabs/pundit#376]
my application has a simple authorization requirments:
- All users can view the data of all controllers.
- Only Admin can create/edit the data.

How can I achieved this without changing controllers of my application? instead I rather do it on application controller once, so all of my cantrollers that inherits from ApplicationController could use the same permissions?

**Comment by nflorentin** [comment]
Something like that should work:

In app_policy.rb (headless policy):
```ruby
class AppPolicy < Struct.new(:user, :app)
  def index?
    true
  end

  def create?
    user.is_admin?
  end

 ### ect ###
end
```

In your application_controller.rb:
```ruby
class ApplicationController < ActionController::Base
   before_action :handle_authorization

   private
     def handle_authorization
       authorize :app
     end 
end
```

Hope it helps someone.

**Comment by jnicklas** [comment]
I'd also like to propose that if your authorization needs really are this simple, then maybe you don't need pundit at all. 😄
