### ISSUE TITLE
Returns Pundit::NotAuthorizedError in production (Heroku) but development environment is fine

### ISSUE THREAD

**Issue by kristophM** [elabs/pundit#377]
I have nothing (to my knowledge) in the code that would cause different behavior for development vs. production. The error returns something like: 

Pundit::NotAuthorizedError (not allowed to company? this #<ActiveRecord::Relation [#<.........
And it happens on the same line as authorize *routes*, where routes is an active record relation. I have a RoutePolicy which inherits from the ApplicationPolicy. 

Also, it looks like it's finding the current_user method and that method is returning an actual user object, so that's not the issue.

Has anyone experienced this? Thanks in advance.

**Comment by jnicklas** [comment]
There is nothing inherent in Pundit that would make it act different in prod. This sounds it's most likely a problem in your application.

**Comment by evanworley** [comment]
This happened to us too. @kristophM did you find a fix?
