### ISSUE TITLE
Why calling Scope#resolve doesn't count as performed?

### ISSUE THREAD

**Issue by TangRufus** [elabs/pundit#378]
Using `SomePolicy::Scope.new(some_user, SomeModel).resolve` in controller doesn't trigger `@_pundit_policy_scoped = true`.
Thus, `Pundit::PolicyScopingNotPerformedError` raised.  

It's possible to suppress it by `skip_policy_scope` or skipping the `action_action`. 

But, why calling `Scope#resolve` doesn't count as _performed_? Is it by design?

Thanks!

**Comment by jnicklas** [comment]
Yes, it's by design. Sort of. We'd have to do some crazy black magic to make that work, and one of the design goals of Pundit was not to do any crazy black magic 😉
