### ISSUE TITLE
policy_scope for namespaced policy

### ISSUE THREAD

**Issue by 5t111111** [elabs/pundit#382]
Thanks to #331, I know that the namespaced policies are supported without creating physical models (e.g. `Admin::Post`), but I don't know how to do the same thing with `policy_scope`.

For the moment, I define a scope for namespaced policy lke the following:

__Controller__

````ruby
class PostsController < ApplicationController
...
  def index
    @posts = policy_scope([:admin, Post])
  end
...
end
```

__Policy__

```ruby
module Admin
  class PostPolicy < ApplicationPolicy
    class Scope < Scope
      def resolve
        scope[1].where(published: true)
      end
    end
  end
end
```

Since `scope` passed to `resolve` is just an `Array`, you have to pick a class object out of it. Are there any other ways to handle namespaced policies along with `policy_scope` ?

**Comment by jnicklas** [comment]
The current behaviour has been deemed incorrect and will be changed in Pundit 2.0. See #351. Not sure if that resolves your question or if there are any issues? I'm not really sure what problem you are having.

**Comment by 5t111111** [comment]
I didn't notice that issue, and yes,  it is enough for my question. I'll take is_a solution untill the behavior is fixed. Thanks!
