### ISSUE TITLE
can not customize rescue_from Pundit::NotAuthorizedError with different name method ( not only use :not_user_authorized )

### ISSUE THREAD

**Issue by hoasung01** [elabs/pundit#384]
- I customize   rescue_from Pundit::NotAuthorizedError and here is my code sample:

         class ApplicationController < ActionController::Base
            rescue_from Pundit::NotAuthorizedError, with: :not_authorized

            protected
            def not_authorized
              render 'shared/unauthorized', layout: 'application', :status => 401
            end
         end

   
        class ProjectsController < ApplicationController

            protected
            def not_authorized
              if current_user
                super
             else
                flash[:alert] = t('labels.project.messages.alert_sign_up')
               redirect_to new_user_registration_path
             end
           end
        end

- It does not work as my expect, I debug and it do not jump into not_authorized code block. 

- But when I change rescue_from method with name is :user_not_authorized as pundit document show then it works ok

- So my expect is I can customize rescue_from with whatever name

**Comment by tiagofsilva** [comment]
Hey guys! I couldn't simulate the problem @hoasung01 mentioned. Maybe he misunderstood that `rescue_from` is something Pundit handles. Well, it's actually from ActiveSupport/Rails (http://guides.rubyonrails.org/action_controller_overview.html#rescue-from). 
@hoasung01: Maybe you have an inheritance problem in your controllers? Just generally try to understand how your app is catching errors and stuff. No problems here, can just be closed.

**Comment by jnicklas** [comment]
This is not specific to Pundit, but rather some kind of problem with `rescue_from`. I suggest asking on StackOverflow if you still have problems.

**Comment by Juksefantomet** [comment]
Adding a comment here just to clarify and to provide a clear answer:

"not_authorized" is a very general term, and the chances of something else using or being linked to a "not_authorized" exception by name is rather large. 

So when creating a truly custom one a naming of the rescue function should be more customized.

Testing and reproducing the above issue did in fact cause an issue with another gem in our project, i did this solely for the testing purposes to make sure it was correct before i added this comment as i discovered this post during my google adventures.

Adding a true custom name to the function on the other hand - pundit worked as intended with  

application controller:

rescue_from Pundit::NotAuthorizedError, with: :pundishing_user

protected
def pundishing_user
    flash[:error] = 'You has been pundished'
    redirect_to root_path
end
