### ISSUE TITLE
Receiving Pundit::AuthorizationNotPerformedError when calling authorize on the action

### ISSUE THREAD

**Issue by CRIZN** [elabs/pundit#388]
Hey all,

I am seeing a really strange issue when trying to perform authorize on my controller#edit action. I have not had any other issues with other actions other than edit.

My policy:
```
  def update?
    company = @current_user.company
    @current_user.has_any_role? :product_editor, { :name => :owner, :resource => company }, { :name => :admin, :resource => company }
  end

  def edit?
    update?
  end
```

My Controller action:
```
def edit                                                  
  @product = policy_scope(Product).find_by_id(params[:id])
  authorize @product                                      
  respond_to do |format|                                  
    format.js {render layout: false}                      
  end
end
```

If you have any ideas let me know, everything else has been really straight forward and have implemented pundit successfully on the rest of my controllers.

**Comment by CRIZN** [comment]
Ignore this one, I had a really strange issue with rails which was causing this. I was able to resolve. Thanks!

**Comment by jeffreyyong** [comment]
@CRIZN Hey, may I know how you solved the problem?
