### ISSUE TITLE
Release new version with authorize

### ISSUE THREAD

**Issue by daniesg** [elabs/pundit#398]
The documentation already says authorize returns an object, but the latest release still returns true. Could we make a release tag and update ruby gems?

**Comment by jnicklas** [comment]
There are multiple issues that still need addressing before 2.0, before they are fixed we won't be cutting a new release.

Documentation on GitHub is necessarily for the master branch. If you want the documentation for the latest released gem it is here: http://www.rubydoc.info/gems/pundit This is also the first link in the README.

**Comment by aried3r** [comment]
On another note, will there be a smaller intermediate release containing [this change](https://github.com/elabs/pundit/commit/b9b2fdc162dd26b7e23029ed7b9414738f8cd614) so we can use it with Rails 5?
