### ISSUE TITLE
Missing description on the documentation

### ISSUE THREAD

**Issue by idoan** [elabs/pundit#407]
> What is this not?
> 
> It's not a failsafe for authorization. Imagine a scenario where there exists a controller action that mutates your service, e.g. PATCH /users/:id. Assuming the update action for the UsersController is not authorized, a request would result in a 500 error due to verify_authorized. However the update would already be persisted leaving a vector for updates being applied without proper authorization.

that description is really vague and missing. the bold text below must be added to the description:

"
... a request would result in a 500 error due to verify_authorized. **Since verify_authorized is an after filter**, however, the update would already be persisted ....
"

**Comment by jnicklas** [comment]
I really don't understand how people misunderstand this feature so damned much. Maybe our documentation is just bad? I honestly don't think adding this one additional bolded whatever line is going to affect people's understanding of this at all.

**Comment by jnicklas** [comment]
I've rewritten the entire section, hopefully it is clearer now.

**Comment by idoan** [comment]
yes, better now. typos exist though

developing you application -> developing your application

If is not some -> It is not some

**Comment by jnicklas** [comment]
Fixed, thanks!
