### ISSUE TITLE
Can't include modules in scope

### ISSUE THREAD

**Issue by earksiinni** [elabs/pundit#411]
I have a policy that looks like this:

``` ruby
class PostPolicy < ApplicationPolicy
  include Helpers

  def update?
    true if author? || admin?
  end

  class Scope < Scope
    include Helpers

    def resolve
      if author?
        scope.where(author_id: user.id)
      elsif admin?
        scope.all
      end
    end
  end

  module Helpers
    def author?
      user.profile.permissions['category'] == 'Author'
    end

    def admin?
      user.profile.permissions['category'] == 'Administrator'
    end
  end
end
```

When I try to send an update to my `PostsController` in Rails using the above code, I get an error like this: `Pundit::NotDefinedError - unable to find policy PostPolicy for #<Post id: 123...`

Backtrace:

```
  pundit (1.1.0) lib/pundit/policy_finder.rb:59:in `policy!'
  pundit (1.1.0) lib/pundit.rb:112:in `policy!'
  pundit (1.1.0) lib/pundit.rb:235:in `policy'
  pundit (1.1.0) lib/pundit.rb:194:in `authorize'
  app/controllers/api/v2/outfit_pictures_controller.rb:12:in `authorize_action'
```

My `authorize_action` hook:

``` ruby
def authorize_action
  authorize Post.find_by_id(params[:id]) || Post
end
```

However, I notice that when I remove the `include Helpers` line from PostPolicy::Scope that it gets rid of the error.

Any idea why this is happening and what some workarounds might be?

**Comment by ce07c3** [comment]
Maybe because it is included before it is defined?

**Comment by jnicklas** [comment]
Yes, I think @ce07c3 is spot on on this one. Rails autoloading will try to load the file and fail, which often causes rather confusing errors. Ruby code is sensitive to definition order, so you're trying to include a module which doesn't exist yet.

**Comment by edwardmp** [comment]
@jnicklas Encountered the same issue today. Can you please tell me what would be a possible way to solve this?

**Comment by jorgegorka** [comment]
If you require the file(s) before you call include then it should work perfectly.
