### ISSUE TITLE
NotAuthorizedError may mislead users to report a 401 Unauthorized, which clearly violates the HTTP spec

### ISSUE THREAD

**Issue by buzzware** [elabs/pundit#412]
Pundit defines this error, and raises it when the authorize method rejects a query. Unfortunately, in this case, Pundit users could easily assume they should return the HTTP status "401 Unauthorized", but this would be against the definition for this status code.

401 Unauthorized : "The request has not been applied because it lacks valid authentication credentials for the target resource" - https://httpstatuses.com/401

 Failing pundit checks rarely has anything to do with a lack of credentials, the failure is more likely a case of 

403 Forbidden : "The server understood the request but refuses to authorize it." - https://httpstatuses.com/403

It gets even worse if you follow a pattern in your client of forcing a logout of the user when they receive a 401, which makes sense when 401 is used correctly. The result is that attempting anything not allowed by a policy causes the user to be logged out, when they should simply be shown an alert and given the opportunity to correct the error or do something else while maintaining their session.

I'm not sure what the mitigation strategy should be without breaking many apps, apart from warning users that NotAuthorizedError should probably lead to a 403 Forbidden, not a 401 Unauthorized.

**Comment by buzzware** [comment]
Oh, I just noticed https://github.com/elabs/pundit#rescuing-a-denied-authorization-in-rails

**Comment by jnicklas** [comment]
Yeah, it's amazing that the HTTP spec gets "Authentication" vs "Authorization" wrong :( As you say, the correct status code is `403 Forbidden` for this kind of thing. We could warn people about this, but using 401 instead of 403 doesn't actually cause any real world problems, and people tend to play fast and loose with status codes anyway, so I'm not too worried.
