### ISSUE TITLE
Can I authorize models before the db lookup?

### ISSUE THREAD

**Issue by grammakov** [elabs/pundit#414]
Documentation says that I need to call the authorize method after the database lookup, like this

```
  def new
    @items = current_user.items
    authorize @items
  end
```

However in this particular case to get things working and avoid user is nil error I need to interchange the lines:

```
  def new
    authorize @items # or authorize Item
    @items = current_user.items
  end
```

Am I allowed to do that? Is it safe?

**Comment by ce07c3** [comment]
You can't authorize on objects you don't have, so the existence of `@items` seems purely hypothetical. What would it be?

I would suggest you check for users in the authentication, not the authorization phase. :)
