### ISSUE TITLE
undefined method `policy_scope` for [...]Controller

### ISSUE THREAD

**Issue by jakehockey10** [elabs/pundit#415]
Hello,

I'm having trouble using the `policy_scope` method in my controller.  It doesn't seem to be recognized even though I'm fairly certain `Pundit` is being included.

My `config/initializers/pundit.rb`:
``` ruby
module PunditHelper
  extend ActiveSupport::Concern

  included do
    include Pundit
    after_action :verify_authorized, unless: :devise_controller?
    after_action :verify_policy_scoped, only: :index
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    flash[:alert] = 'Access denied.'
    redirect_to (request.referrer || root_path)
  end

end

ApplicationController.send :include, PunditHelper unless Rails.env.development?
```

My `app/controllers/application_controller.rb`:
``` ruby
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  protect_from_forgery with: :exception

  if Rails.env.development?
    include Pundit
    after_action :verify_authorized, unless: :devise_controller?
    after_action :verify_policy_scoped, only: :index

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private
      def user_not_authorized
        flash[:alert] = 'Access denied.' # TODO: make sure this isn't hard coded English.
        redirect_to (request.referrer || root_path) # Send them back to them page they came from, or to the root page.
      end
  end

end
```

And my `app/controllers/enterprises_controller.rb`:
``` ruby
class EnterprisesController < ApplicationController
  before_action :set_enterprise, only: [:show, :edit, :update, :destroy]

  def index
    @enterprises = policy_scope(Enterprise) # error shows up here!
    authorize @enterprises
  end

  ...

end
```

I'm doing my best to refer to and understand the documentation here: https://github.com/elabs/pundit#user-content-scopes

**Comment by jakehockey10** [comment]
http://stackoverflow.com/questions/39217284/rails-5-pundit-gem-testunit-testing-policy-scopes

**Comment by mode-x** [comment]
Do you have the policy class for the "EnterprisesController"?

Also what is the error message you are getting?

**Comment by jakehockey10** [comment]
I was getting an unknown method error.  The workaround is to just `include Pundit` in `ApplicationController` rather than wrapping that in an `if` block conditional to development.  My tests would also misbehave quite frequently unless I periodically made changes to the `pundit.rb` initializer every so often.  Is this because I'm Rails 5 maybe?

**Comment by ce07c3** [comment]
Why don't you use controller concerns for this? No need to monkey patch in the initializers. 

That being said, 'spring stop' is your friend as thr Speing loader seems oblivious of changes in config and lib.

**Comment by jakehockey10** [comment]
Thanks for the suggestion. I was following a lot of what I saw in the wiki. Someone mentioned performance concerns as to why the monkey patching was necessary for them. It seems to not be a problem for me, performance-wise, if I do as you suggest and just have this logic associated with the controllers. Thanks again

**Comment by ce07c3** [comment]
:) happy to help!
