### ISSUE TITLE
Pundit - getting started 

### ISSUE THREAD

**Issue by MincePie** [elabs/pundit#417]
I am having a lot of trouble figuring out how to get started with pundit in my Rails 4 app. I read this article https://github.com/elabs/pundit/issues/322 and cringe when learning pundit is described as easy. 

I don't think I have made much progress in the 2 years I have spent trying to figure it out.

I have outlined my current issue and problems in this post: http://stackoverflow.com/questions/39382294/rails-4-pundit-scopes-getting-started

Please could you help me with some advice on getting started.

Thank you

**Comment by mode-x** [comment]
Check the ProjectPolicy...i don't see the reason why you should have an
argument passed to resolve. According to the documentation that is wrong.

**Comment by MincePie** [comment]
Hi - thanks for the note. You mean my Project Eoi Policy right? I have the resolve method on that to decide whether the current user is the user who created the project or otherwise.  In order to decide that, I need the resolve method to process a project_id. What is it that you can see that is wrong with that?

**Comment by mode-x** [comment]
I see User, Profile, Project, Eoi Classes but no ProjectEoi Class and
definately no ProjectEoi Controller...shouldn't there be a Project Class
and a Controller. Your model relation is correct and with the right classes
you can handle scoping the pundit way without passing an argument to resolve

**Comment by MincePie** [comment]
Hi - as I noted in my post, I have 2 policies for 1 controller. You can see in the Eoi Controller index action that I use the Project Eoi policy as one alternative.  I don't know how to achieve scoping in the 'pundit way'. I've outlined about 5 different attempts in this post: http://stackoverflow.com/questions/39186881/rails-4-pundit-scoped-policy-for-index. I can't find a way to do this that works.

**Comment by mode-x** [comment]
In my humble opinion i think you don't need a ProjectEoi policy...just keep
it simple. By simple i mean delete the ProjectEoi policy create a
ProjectPolicy. In the resolve method for PojectPolicy try:

   - scope.where(eoi_id:  user.eois)

**Comment by MincePie** [comment]
Thanks for the thought. I'm not sure that is going to help me. The controller action that displays the eoi is the EoI controller. If I write that resolve method in the Project Policy (setting aside for a moment what I then would do to manage the project scopes that are to be applied to the project actions). I'm not sure I've understood your thought on how to simplify my attempt. I am trying to display eois on a project to specific users based on whether they are the user that owns the project, or they are a user who created an eoi.

**Comment by mode-x** [comment]
"I am trying to display eois on a project to specific users based on
whether they are the user that owns the project, or they are a user who
created an eoi"...to get this in the scope use:

   - scope.where(id:  user.eois.ids) - this will select id from eois where
   id IN [array containing ids of user specific eois] this should work

**Comment by jnicklas** [comment]
I think suggestions on how to improve the documentation are very helpful, and we'd definitely like to make Pundit even easier to understand and use, but there isn't really anything actionable in this issue, so I don't really know where to go from here. I'm closing this issue, but if you have any concrete suggestions on what we could do to improve our documentation please let us know in a separate issue.
