### ISSUE TITLE
undefined method `?` for @query

### ISSUE THREAD

**Issue by ahmgeek** [elabs/pundit#422]
I've a very weird error, I have `Doorkeeper` as API authentication mechanism, I don't use it fully for now, but I kinda save some data on it's tables. so the table name is `oauth_applications` and the class that respond to that table is `Doorkeeper::Application`
so I made a model `models/oauth_application.rb` :

```
class OauthApplication < Doorkeeper::Application
end
```

and policy `policies/oauth_application_policy.rb`:

```
class OauthApplicationPolicy < ApplicationPolicy
  attr_reader :user, :application

  def initialize(user, application)
    @user = user
    @application = application
  end

  def update?
    true
  end
end
```

in the end point:

```
desc 'Update Application', headers: authenticated_headers
   params do
     optional :name, type: String, desc: 'App name
     optional :preferences, type: String, desc: 'App preferences'
   end

   put do

   app = OauthApplication.find_by!(uid: headers['X-Client-Id'])
   authorize app
   app.update!(params)
   present app, with: V2::Entities::OauthApplicationEntity
  end
end
```

so I alwyas have the error `Error: undefined method`?' for #OauthApplicationPolicy:0x0000000bf5e230`I've tried to trace the error until I faced it in pundit, the query param here:
https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L65-L67
query always have the value`"?"` then raise an exception.

**Comment by jnicklas** [comment]
I honestly don't really know what's going on here. Are you maybe including Pundit in a scope which is not a Rails controller.

Anyway this kind of question is probably better asked on StackOverflow (as evidenced by the slow response here ;))
