### ISSUE TITLE
Pundit v1.2.0?

### ISSUE THREAD

**Issue by mrcasals** [elabs/pundit#423]
Hi! 

First of all, thanks for the work on this gem! 

I was struggling to make this code work (from the README), since `authorize` kept returning `true`:

``` ruby
def show
  @user = authorize User.find(params[:id])
end
```

Then I saw that the fixes that make this code work are not released in any version, they are only in `master`. Could you please release a new version? There are quite a few changes since the last version, too:

https://github.com/elabs/pundit/compare/b0bdfbc0db601ea4cc6cfcb243a657396c3e0f82...master

Thank you!

**Comment by abuisman** [comment]
I had the same issue and then realised (after going through the issues) that this is not released yet.

How compatible/stable is master? I might use it in my gemfile instead for now (hobby-ing on something).

**Comment by aried3r** [comment]
Yeah, especially https://github.com/elabs/pundit/commit/b9b2fdc162dd26b7e23029ed7b9414738f8cd614 is very important to our own project.

@abuisman, we use the master version inside our own project and have not faced any issues so far.

**Comment by ce07c3** [comment]
@jnicklas maybe add more maintainers?

**Comment by ce07c3** [comment]
Project seems abandoned, maybe fork and release "pundit2"?

**Comment by abuisman** [comment]
@aried3r Thank you for the information, I went ahead with master.

@ce07c3 That seems a bit quick, the last commit was 4 months ago and if you look at the history: https://github.com/elabs/pundit/commits/master there have been some pretty consistent commits in the period before that. I have no idea what is going on right now, but maybe there is some other way to get in touch with the author?

**Comment by ce07c3** [comment]
Imho a project that has no commits in 4 months and is actively used as this one, means the maintainers have abandoned ship. We need more frequent updates.

**Comment by abuisman** [comment]
@ce07c3 I agree that there should be some more activity, which for the maintainers would probably mean adding some maintainers, but creating a fork and advertising that as 'version 2' would just create a more diffuse set of 'pundit-like' or 'pundit-version' gems.

Have you tried getting in touch with elabs? They have contact information on their organisation page.

**Comment by jnicklas** [comment]
Hello, I'm here, and this project is not abandoned, just low activity. Frankly I don't spend a lot of time working on open source these days, and when I was at Elabs this was mainly my project, which is why they don't put much time into it either.

The main blocker for releasing a new version are the changes we want to make to the namespace API, see #351. My intention was to bump the version number to 2.0 and to also include this change, which is a breaking change, which is why it can't be released in a minor version.

As for how much maintenance this project needs: please recall that this project has like 100LOC. It is essentially "finished" for the most part. Yes there is little activity, but there really doesn't *need* to be either, because honestly there isn't much to do.

**Comment by jnicklas** [comment]
I will spend some time this week or next week going through the issues and I will try to release a new version.

**Comment by abuisman** [comment]
@jnicklas Thanks for the update. I quite agree with regards to it being done. Not sure what more could be done besides some documentation (from looking at the issues).

Looking forward to the 'new version'.

**Comment by ce07c3** [comment]
Not much to do vs. no release despite changes :) thanks for taking care of it!

**Comment by jnicklas** [comment]
I'm working through the currently open issues now. Closing this as it's not really an issue. Hopefully I can make a new release today.

**Comment by electrickite** [comment]
I realize this issue was closed, but has there been any movement on the next version of Pundit? Even releasing a few of the minor features added to master would be a big win. 

@jnicklas What are the blockers to a release? Do you need testers?

**Comment by ce07c3** [comment]
@jnicklas can you please add more maintainers?

**Comment by FX-HAO** [comment]
Any progress?
