### ISSUE TITLE
Adding a policy for Index action, when authorization depends on a nested model?

### ISSUE THREAD

**Issue by amingilani** [elabs/pundit#425]
This is a pundit question since this use case isn't defined in the pundit docs.

I have an event class with many organizers, and the resources are nested so, to view an event's organizers, I have to access: `/events/23/organizers`

The index controller for organizers is like so:

```
Class OrganizersController < ApplicationController
  def index
    @wedding = Wedding.find(params[:wedding_id]
    @organizers = Organizer.where(wedding: @wedding)
  end
end
```

Trouble is, how do I allow pundit to authorize the index action for `OrganizersController` and only if  `@wedding.organizers.find(user: current_user).present?`

They're two entirely different models, and the authorization of one depends on other.

**Comment by amingilani** [comment]
Maybe we should add use cases to the docs?

**Comment by jnicklas** [comment]
This question has been asked a few times, and there is no "one" answer. The way I usually do it, is to add a `list_organizers?` predicate to the wedding policy and then:

```
authorize(@wedding, :list_organizers?)
```

It's not terribly elegant though.
