### ISSUE TITLE
Rails_admin not picking Models when Pundit used.

### ISSUE THREAD

**Issue by minu10** [elabs/pundit#431]
Hi,

I'm using Devise-gem for authentication and Pundit-gem for Authorization with Rails_Admin gem for admin. In config/initializers/rails_admin.rb, all the model files are seen on admin dashboard only if I comment the Pundit config with rails_ admin like as shown below:
## == Pundit ==
#config.authorize_with :pundit - 

![screen shot 2016-11-19 at 00 05 46](https://cloud.githubusercontent.com/assets/23400734/20523385/ac57fdcc-b0ac-11e6-9f98-0cd172fe3676.png)

Now if I uncomment the line above because I'm using Pundit, the models are not seen at all.
config.authorize_with :pundit 

![screen shot 2016-11-21 at 13 50 10](https://cloud.githubusercontent.com/assets/23400734/20523379/a4d3f9d4-b0ac-11e6-9890-40ae5b227a5d.png)

Can you fix this issue?

Thanks & Regards,
Minu

**Comment by ce07c3** [comment]
Have you even authored any relevant policies? This doesn't seem to be an issue with Pundit. @minu10

**Comment by minu10** [comment]
yes, there are policies created(or extended) as per Pundit instructions for all models that you see in attachment 1's left pane. Now I cannot understand what you mean by 'authored any policies'?If only one line - commenting or uncommenting makes basic difference that all my models are lost in rails_Admin view, I'd believe some config conflict with Rails_Admin

**Comment by ce07c3** [comment]
Then it's probably a good idea to post it in the `rails_admin` gem's issue tracker. 😃

**Comment by minu10** [comment]
Well! it can be. I'll try there as well. Thx.

**Comment by ce07c3** [comment]
@minu10 have you written any tests for your policies? Can you copy&paste one of the policies, including ancestors?
