### ISSUE TITLE
verify_policy_scoped not satisfied when not using policy_scope

### ISSUE THREAD

**Issue by bennyzr** [elabs/pundit#436]
When calling OrderPolicy::Scope.new(current_user, Order).resolve directly I get a Pundit::PolicyScopingNotPerformedError. Using policy_scope(Order) does not result with this exception. I would think that either should satisfy the verify_policy_scoped method.

**Comment by ce07c3** [comment]
I would not expect that. If you call the library instead of the helper, it should not depend on the controller. 

Why not call `policy_scope(Order)`?

**Comment by bennyzr** [comment]
I need to pass a parameter to resolve.

**Comment by ce07c3** [comment]
You are - `Order`?

**Comment by bennyzr** [comment]
That's pretty much what I ended up doing.

**Comment by ce07c3** [comment]
👍 Another option is to wrap the scope (as in working *with* the library for lack of "better" alternatives).
