### ISSUE TITLE
authorize chain not work when use rubygems.org source

### ISSUE THREAD

**Issue by astonfu** [elabs/pundit#439]
I use pundit 1.1.0, first just use it with Gemfile default, authorize chain not work.

Use pry cd the source code, finding that it return true in authorize(record, query = nil) on line 199.

But the code on github is return record on line 189.

 So switch to github source, it works !

**Comment by heliohead** [comment]
Same for me ¬¬

**Comment by andi-dev** [comment]
Same here.

**Comment by quolpr** [comment]
The same for me

**Comment by quolpr** [comment]
Oh, I understand, it will be included in future releases

**Comment by kjleitz** [comment]
Yup, same here!

**Comment by antoineBernard** [comment]
Same here ^^°

**Comment by rafaelcgo** [comment]
Same here...
Just spent something trying to figure why authorize was returning `true` instead of `record`... :(

**Comment by omkarmoghe** [comment]
FWIW chaining the `authorize` call works when you don't specify a specific action to check. For example `authorize obj` returns `obj` but `authorize obj, :action?` returns `true`/`false`
