### ISSUE TITLE
Pundit dealing with policies in certain views (or somehow associated with)

### ISSUE THREAD

**Issue by Lubmes** [elabs/pundit#445]
I like it in my views when actions are only visible after a pundit check.

Now the issue arises with an action on some data showing, that should not be actionable in that particular view (in my case an order that has been confirmed, should not allow a user to make edits to his or her address).

It would be nice and clean if pundit still would pick up on it and I would not have to clutter my view with some if-statement doing an extra check, effectively saying: _You do not have rights when you are in this particular view to make this CRUD action._

Could I centralise this in Pundit? Would you recommend building a separate helper for Pundit for this, since Pundit is just POROs?  
I understand you'd want Pundit to deal with the actual controller action dealing with the database, etc. but is there maybe a clever way of dealing with view management to? 

Is it maybe an idea to add something in your documentation about this, like:  
When concerned with certain policy in view, add this or that, here or there.

Ultimately I would like my Pundit `<% if policy(@post).action? %>` to also stop rendering when not in the right view.

**Comment by damien** [comment]
I've done something similar in applications I've worked on. In my own experience, you can just make multiple policies for the same sets of data and choose the appropriate policy depending on the context.

In your case, you could make an additional policy to handle unconfirmed orders. IIRC Pundit already has hooks you can use to dynamically choose a policy for an object (see [Manually Specifying Policy Classes](https://github.com/elabs/pundit#manually-specifying-policy-classes) in the README).

**Comment by rystraum** [comment]
Unrelated to Pundit, but a way to achieve what you describe is by sparating actions/buttons/menus into its own partial/helper and do the checking there. Then just use the same partial/helper anywhere that resource is concerned.

I personally go with partials because I can:

* open it via `CMD + P` in Sublime Text
* I can specify full partial paths to make it unambiguous
