### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by mrneiverth** [elabs/pundit#458]
Hello, I'm trying to install this gem which is used in a gemfile repository. I tried bundle install, bundle update, but apparently, I got a loop error.

`rails s
https://github.com/elabs/pundit (at master@8b2d638) is not yet checked out. Run `bundle install` first.
bundle install
...
Bundle complete! 22 Gemfile dependencies, 77 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
`
Does someone have any idea ?
I'm using rails 5.0.2
I'm using ruby ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by damien** [comment]
Could you include your Gemfile? From the error message you provided it seems like you're referencing git source of Pundit, which may be your problem.

**Comment by mrneiverth** [comment]
Sure!

`source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# pundit for authorization
gem 'pundit', :git => 'https://github.com/elabs/pundit' 
#.. more gems
`

**Comment by damien** [comment]
Change

```
gem 'pundit', :git => 'https://github.com/elabs/pundit'
```

to

```
gem 'pundit'
```

Then run `bundle install`. In general, you should prefer to pull a gem from Rubygems rather than the git source unless you're certain you need particular changes that haven't yet been released.

**Comment by mrneiverth** [comment]
Was just it, thanks!

**Comment by mrneiverth** [comment]
Hi,
I'm back with the same error. In the project that I need to install, I need to use the authorized method, which is used from the git, and not from the rubygems because from rubygems it return a boolean, and from git returns an object.

I tried some new stuffs, as removing all my gems from my computer, but I still get the error. 
`https://github.com/elabs/pundit (at master@8b2d638) is not yet checked out. Runbundle installfirst.
`
I'm using _rvm_, and my team is using _rbenv_. Could be something with my _rvm_ ? 
I'm installing _rbenv_ to test it. when it going to finish, I will update here.

**Comment by mrneiverth** [comment]
I setup rails again and now its really working :D
