### ISSUE TITLE
force calling a different method instead of current_user

### ISSUE THREAD

**Issue by dkumar431** [elabs/pundit#464]
I am trying to integrate pundit to my rails cms app. 
We have two different methods "current_user"  and "current_manager".

As per the pundit documentation,

> The first argument is a user. In your controller, Pundit will call the current_user method to retrieve what to send into this argument

I want to force to pundit to call current_manager method instead of current_user method.
Is this possible somehow?

**Comment by zach-taylor** [comment]
@dkumar431 Pundit technically calls `#pundit_user` in your controller, so you can override it. See here: https://github.com/elabs/pundit#customize-pundit-user

**Comment by dkumar431** [comment]
Yes, I too figured out the same. Thanks a lot for your help.
