### ISSUE TITLE
Cannot allow permitted Attributes for a array

### ISSUE THREAD

**Issue by itskeerthivasan** [elabs/pundit#465]
if its a tag_list is array like(:tag_list => [] we do in strong params) how can we allow it via pundit's Permitted Attributes 

![image](https://user-images.githubusercontent.com/14290574/27251132-0214539c-535e-11e7-90a7-f716f21fe4c2.png)

**Comment by itskeerthivasan** [comment]
it can be added by [:title, :body, [:tag_list => []]].

**Comment by jaykilleen** [comment]
This has worked for me but a bit stumped on how to call it in the veiw to decide if the field should be shown or not. 

Using the tag list example above, the structure ends up looking like

`[:first_name, :last_name, :email, [{:role_ids=>[]}]`

`<% if policy(model).permitted_attributes.include?(:role_ids) %>` **X**
`<% if policy(model).permitted_attributes.include?([:role_ids]) %>` **X**
`<% if policy(model).permitted_attributes.include?(role_ids:=> []) %>` **X**

**Comment by jaykilleen** [comment]
ok looks like the answer is:

`policy(model).permitted_attributes.flatten.include?({:role_ids=>[]})` 

for anyone else that might get stumped by this.
