### ISSUE TITLE
Use policy_scope with custom class

### ISSUE THREAD

**Issue by laertispappas** [elabs/pundit#482]
Hello I would like your feedback on something that I am implementing. 
I have explicitly required all actions in my application controller to authorize all requests:

```ruby
class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized
end
```
Given I have a `posts controller` with an `index` action I would like to fetch all posts that are published for normal users. So the following is implemented in `PostsController` and `PostPolicy`:

```ruby
class PostsContoller
  def index
     posts = policy_scope(Post)
     render json: posts
   end
end

class PostPolicy < ApplicationPolicy
  class Scope < Scope
     def resolve
        scope.published
     end
  end
end
```   

What I would like to do is to create and `AdminPollPolicy` that will be used from an `Admin::PostsController` in order to fetch all `posts` regardless of their published status, thus I have the following:

```ruby
  class Admin::PostsController
    def index
      # posts = policy_scope(Post) # <== this will not work since it will call PostPolicy instead
     AdminPostPolicy::Scope.new(current_user, Poll).resolve
    end
  end

class AdminPostPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      user.admin? ? scope.all ? scope.none
    end
  end
end
```

However the above will raise a `PolicyScopingNotPerformedError` since we bypassed `policy_scope` method that mutates the corresponding instance variable in order to pass PolicyScope authorization:

```ruby

def policy_scope(scope)
    @_pundit_policy_scoped = true
    pundit_policy_scope(scope)
  end
```

Am I missing something here? What would be the correct way to implement the above?
Thanks.

**Comment by laertispappas** [comment]
Maybe this is a duplicate of #480

**Comment by ingemar** [comment]
👀

**Comment by K-Eo** [comment]
You can use a namespace Policy:
```ruby
policy_scope([:admin, Post])
```
Check this PR #392.

**Comment by laertispappas** [comment]
@K-Eo Thank you for your feedback. It looks like that is the way to go. Thanks.
