### ISSUE TITLE
Model-level authorization

### ISSUE THREAD

**Issue by hesham** [elabs/pundit#485]
Is there any interest in  adding authorization at the model level as a secondary/alternative line of defense to Pundit? Something similar to this:

```ruby
module PunditModel
  extend ActiveSupport::Concern

  included do
    before_create :check_if_creatable
    before_update :check_if_updatable
    before_destroy :check_if_destroyable
    
    attr_accessor :current_user
  end

  private
  def check_if_creatable
    raise_unauthozied unless Pundit.policy(current_user, self).create?
  end

  def check_if_updatable
    raise_unauthozied unless Pundit.policy(current_user, self).update?
  end

  def check_if_destroyable
    raise_unauthozied unless Pundit.policy(current_user, self).destroy?
  end

  def raise_unauthozied
    raise Pundit::NotAuthorizedError, "You are not authorized to perform this action"
  end
end
```

Note: This can also be extended to add attribute-level authorization using `permitted_attrubutes_for_create`, `permitted_attrubutes_for_update`, etc.

Using validation (in case of create and update) is another idea.

**Comment by ce07c3** [comment]
It makes little sense, as it dilutes the model with authorization concerns. While perfectly possible, it would mean that for every save you perform, Pundit would authorize the object. What if you want to save the object without a current user? How does the current user even get set on the model? Worse, skipping callbacks will lead to messy code, and at some point you will want to skip these callbacks.

**Comment by hesham** [comment]
@ce07c3 Thanks for the response. You raise for good points. Here are some thoughts:

>  it would mean that for every save you perform [authorization]

Isn't that what it does right now when you call `authorize @resource`?

> How does the current user even get set on the model?

This is the part I'm not sure about.

> What if you want to save the object without a current user?

"run insecurely" block can be used to skip, but the default is on

**Comment by ce07c3** [comment]
@hesham 

I wouldn't say so, please refer to the open/closed principle of object oriented programming. `authorize @resource` is external to `@resource`, whereas your suggestion means authorization is an elementary component of the model.

I also wouldn't perform double authorization checks. Just make sure the primary ones work. :)
